### ISSUE TITLE
map_dbl() permits integer values

### ISSUE THREAD

**Issue by yutannihilation** [hadley/purrr#100]
I wonder why this won't fail, since I expect the returned type is integer, which is not the type `map_dbl()` expects.

```r
map_dbl(1L:2L, as.integer)
#> [1] 1 2
```

But, it seems that `map_dbl()` always returns double values even when the results of `.f` are integer values.

```r
map(1L:2L, as.integer) %>% map(is.double)
#> [[1]]
#> [1] FALSE
#> 
#> [[2]]
#> [1] FALSE

map_dbl(1L:2L, as.integer) %>% map(is.double)
#> [[1]]
#> [1] TRUE
#> 
#> [[2]]
#> [1] TRUE
```

I guess this is a limitation of `vapply()` and you are aware of this, since the help of `map()` says
"`map_lgl() returns a logical vector, map_int() an integer vector, map_dbl(), a numeric vector, map_chr(), a character vector.`", not `a double vector`.

 If this is unavoidable, I suggest renaming `map_dbl()` to `map_num()` or something to avoid confusion.

**Comment by hadley** [comment]
It's super strict now. I'm not sure I like it more, but it does exactly what it says on the tin.

**Comment by yutannihilation** [comment]
Super strict! Thanks!
