### ISSUE TITLE
access to keys and values from list in `map`

### ISSUE THREAD

**Issue by koaning** [hadley/purrr#102]
This may be a feature request more than a bug. 

I wonder if there might be an elegant way to map over a list and also have access to the keys instead of just the values. I currently use `map2` with the `.y` param set to `names(.)` of the preceeding object (which seems like a verbose way of doing it). 

This may be an elaborate example, but here is an example of when it might be nice to also have keys. 

```
create_df <- function(dist_func, n_means, means){
  data.frame(
    n_100  = 1:n_means %>% map_dbl(~ dist_func(100) %>% mean),
    n_200  = 1:n_means %>% map_dbl(~ dist_func(200) %>% mean),
    n_300  = 1:n_means %>% map_dbl(~ dist_func(300) %>% mean), 
    n_1000 = 1:n_means %>% map_dbl(~ dist_func(1000) %>% mean)
  )
}

plot_df <- function(df, distname){
  ggplot() + 
    geom_histogram(data=df %>% melt, aes(value, fill = variable), binwidth = 0.01) + 
    facet_grid(variable ~ .) + 
    ggtitle(paste('distribution of means from', distname, 'distribution'))
}

list(gauss = rnorm, uniform = runif) %>% 
  map(~ create_df(., 200)) %>% 
  map2(names(.), ~plot_df(.x, .y))
```

I really like what this project is doing by the way. This package effectively removes the need for for loops in a lot of simulation cases that I have and the resulting code seems a lot easier to understand/maintain.

**Comment by lionel-** [comment]
I've also thought about this since this is a fairly common application. Could be called `map_with_names()` (somewhat lengthy), `labelled_map()`, `named_map()` or `named_map2()`?

Or `map_xn()` with each letter representing the type of argument. This one would have the advantage of being more general. Could be a good pattern for package-specific mapping functions as well.

**Comment by hadley** [comment]
I'm hesitant to add support for this since the pattern is already also simple, and there are already a lot of map variants.
