### ISSUE TITLE
Keep attributes in map&co

### ISSUE THREAD

**Issue by stefanfritsch** [hadley/purrr#104]
Hi, 

I assume there is a good reason against it, but currently map will lose e.g. the data.table class. 

You could avoid that by keeping the class or even more attributes (interesting, e.g. for haven) from the input. Perhaps by turning either map or output_hook into an S3 generic; or a parameter keep.attributes, that accepts TRUE, FALSE or a vector of attributes to keep?

Thx
Stefan

**Comment by lionel-** [comment]
Maybe we should use `x[] <- lapply(x, f, ...)` internally to give subsetting methods a chance to restore the attributes.

We didn't do it that way because the `[<-.data.frame` method does not behave correctly, but we could bypass it for data frames.

**Comment by lionel-** [comment]
Another reason for this change is that `map()` would behave more like `map_if()` / `map_at()` which both use the subset-assignment method.

We could test each S3 class sequentially with `utils::getS3method("[<-", class)`. We use the first one that exists and once we reach the `"data.frame"` class, we bypass it to use our own code.

The thing is, the data.table subset-assignment method has the same shortcoming as the data frame one. It expects the same number of rows as the input data frame, so it's not possible to have:
```r
data <- mtcars
data[] <- lapply(data, summary)
```
In dplyr terms, this only supports mutating operations. Hence if we implement this way, data tables and data frames mappings would not behave symmetrically.

**Comment by hadley** [comment]
@lionel- a slightly simpler alternative would be to provide our own generic - it provide a default method that just called `[<-` and a method for data frames

**Comment by lionel-** [comment]
Ah yes that would be simpler and solves the dispatch of data frames.

How would you handle attributes restoration for data frames? Should we copy everything or just the classes? I can't see a problem with restoring all attributes but I may be missing something.

Also we should only add the `tbl_df` class if the input was a bare data frame.

**Comment by hadley** [comment]
I think restoring all attributes is reasonable.

**Comment by stefanfritsch** [comment]
You could check if every element of the output list has

* the same length. If not it's no longer a data.frame so don't copy classes and rownames.
* the same length as the input has rows. If true copy everything, else create new rownames.

**Comment by hadley** [comment]
I think this discussion suggests we may need a different primitive, `map_df` maybe.

**Comment by stefanfritsch** [comment]
I really like the elegance of treating all list-like types identically.

In my opinion, it mostly comes down to a check whether the output is still compatible with the the basic assumption of a data.frame that it can be presented in table-form. The rest is mostly due to technical issues with the [] and not philosophical problems.

**Comment by hadley** [comment]
I disagree because as soon as you start trying to guess the correct type of output you are going to occasionally get it wrong - that means you now have a function that 1% of the time (due to output lengths aligning by chance) returns a data frame instead of a list.

**Comment by lionel-** [comment]
I think Hadley is right.

This way it's clear that if the output does not have the same number of rows in each col, `map_df()` fails. And `map()` could be used with such outputs without having to explicitely downcast to a list first.

@hadley should the suffix be `_df`? We already have `_d` with `cross_d()`. I think I prefer `_df` actually. Still time to rename `cross_d()` to `cross_df()`?

**Comment by hadley** [comment]
@lionel- yeah, I like `_df` better too, and I don't think it's too late to rename (although we should probably provide alias to existing function with warning)

**Comment by lionel-** [comment]
> that means you now have a function that 1% of the time (due to output lengths aligning by chance) returns a data frame instead of a list.

Ah so you think we should not use `[<-` after all?

Then we should think about downcasting `.x` to a list in `map_if()` to have consistent behaviour. Once I was surprised by the output of `map_if()` with a `lazy_dots` object.

**Comment by hadley** [comment]
I think the current behaviour of `map()` is ok because it always returns a data frame output for data frame input (i.e. it's type-stable)

**Comment by lionel-** [comment]
hmm... How would `map_df()` differ from `map()` then? Apart from always trying to coerce the output to data frame even if the input was something else?

**Comment by stefanfritsch** [comment]
I think he referred to my point that it might result in a non-data.frame if lengths don't align.

**Comment by lionel-** [comment]
ok here is another idea:

* `map_df()` coerces to data frame and copy relevant df attributes if input was a data frame.
* `map()` always downcasts to a bare list

Then when users need to copy attributes they can do:
```r
x[] <- map(x, f)
```

**Comment by lionel-** [comment]
> Then when users need to copy attributes they can do:

though that doesn't help when the input should not be rewritten by the output.

**Comment by stefanfritsch** [comment]
And lists might also have attributes that should be copied, too.

**Comment by lionel-** [comment]
yes but it may not be a bad thing to force users to formalise "lists with attributes" as S3 objects

**Comment by stefanfritsch** [comment]
Correct me if I'm wrong, but as I see it then they'd have to write their own methods for purrr so map&Co don't destroy those objects when they encounter them. Many packages won't do that for their classes so that means either no purrr or hacks.

**Comment by lionel-** [comment]
no the idea is that they'd just have to write a general-purpose `[<-` method.

**Comment by stefanfritsch** [comment]
Let me again point to the haven package where the support for labelled objects is extremely rudimentary. And that is by Hadley.

I understand that you dislike adding parameters as that might end like the help pages of base graphics functions, but in this case it is imho a valid question: Should the function `map()` try to preserve as much as possible of the input while doing the mapping or should it start over with a clean slate. 

In my opinion that is something R would solve via parameter but if it ends with `map_preserve()` and `map_renew()` I'd be just as happy. I'd just like to have a function into which I can throw everything list-like. :)

**Comment by lionel-** [comment]
The advantage of relying on `[<-` is that packages can implement attributes restoration the proper way (though it's true that a simple copying operation should be sufficient in most cases). The disadvantage is that sometimes the `[<-` does not work quite the way we want it as with data frames.

Just to continue with my idea (Hadley please stop me if I'm not making any sense). When it's not desirable to overwrite the input with the output, we could have a new verb or adverb. E.g. with an adverb:
```r
preserving <- function(.x, ..f, ...) {
  out <- .x
  out[] <- ..f(.x, ...)
  out
}

x <- object %>%
  preserving(map, fun, args)
```

I agree it'd be better to have just `map()` work. This means either using `[<-` internally or simply copying attributes. The problem I see with this is that `map()` and `map_df()` would both handle data frames each in their own way. Hence my idea of having `map()` downcast to a simple list by default, but that may be going overboard indeed.

**Comment by lionel-** [comment]
> The problem I see with this is that map() and map_df() would both handle data frames each in their own way.

Just realised it would also make the API heavier: we'd need `map_df_if()` and `map_df_at()` as well since the `_if` and `_at` versions are quite useful with data frames.

In the end it may be better to have our own generic and data frame method, with the default using `[<-`. The current `map()` behaves nicely except for the problem reported by Stefan.

**Comment by hadley** [comment]
As I think about this more, I think `map()` should stick to returning a bare list - we have variants for other types `map_int()`, `map_dbl()`, ..., `map_df()`, so I think it's reasonable that other packages might want to define their own variants for non base types.
