### ISSUE TITLE
by_slice() discards attributes

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#106]
e.g.

``` r
diamonds %>%
  slice_rows("cut") %>%
  by_slice(map_if, is.numeric, ~ .x / sum(.x))
```

The factors become integers.

**Comment by lionel-** [comment]
@hadley I wonder if we should come up with our own extensible system to preserve attributes that could be reused in other packages.

We'd need a generic for preserving attributes:

* When input and output have the same number of elements (this is the use case behind `input[] <- output`)
* When they don't have the same number of elements (and issuing an error when it doesn't make sense to preserve in this case).
* When the output is raw (stripped of any attrs). For example a factor transformed to an integer vector.
* Accept dots so that methods can have their own flags? For example, the data frame method could make it optional to accept a different number of rows than the input.

Then a generic for concatenating vectors while preserving attributes. The opposite of `c()` which deliberately discards them. Canonical example: [joining factors](http://stackoverflow.com/questions/8229904/r-combining-two-factors). Could be called `concat()`, or `p()` for "preserving `c()`"

Or would that be too ambitious?

**Comment by hadley** [comment]
I think `by_slice()` will be moved to dplyr, probably with a different name
