### ISSUE TITLE
map2 drops names

### ISSUE THREAD

**Issue by philipdarling** [hadley/purrr#107]
I noticed that the behaviour of map and map2 differ in terms of handling of named lists. Specifically, map keeps the names but map2 does not:

```{R}
x <- list(a = 1, b = "fun", c = 1:15)
purrr::map(x, ~.)  # keeps names
purrr::map2(x, names(x), .f = function(x, y) x)  # drops names
```

It would be great if map2 also kept the names! Thanks.

**Comment by lionel-** [comment]
This is by design, see #64

**Comment by philipdarling** [comment]
Thanks Lionel!
