### ISSUE TITLE
Allow tweaking output of rows-based functionals

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#112]
e.g., https://twitter.com/mikelove/status/652502458946703360

When `.f` returns atomic vectors, these are row-binded together. A `.row` column indicates the index of each value in the original output vector. It may be more intuitive to return in wide format instead.

Could be solved by adding a `.collate = c("rows", "cols")` argument to these functions.

Taking this example:
```r
p <- expand.grid(mean = 1:5, sd = seq(0, 1, length = 10))
p %>% map_rows(rnorm, n = 5)
```

Collating over rows (current behaviour):
```r
# Also this arrangement isn't ideal and shouldn't be sorted by .row
> Source: local data frame [250 x 4]

    mean    sd  .row  .out
   (int) (dbl) (int) (dbl)
1      1     0     1     1
2      1     0     1     1
3      1     0     1     1
4      1     0     1     1
5      1     0     1     1
6      2     0     2     2
7      2     0     2     2
8      2     0     2     2
9      2     0     2     2
10     2     0     2     2
..   ...   ...   ...   ...
```

Collating over cols:
```r
Source: local data frame [50 x 7]

   mean      sd   .out1  .out2   .out3   .out4  .out5
  (int)   (dbl)   (dbl)  (dbl)   (dbl)   (dbl)  (dbl)
1     1 0.00000 1.00000 1.0000 1.00000 1.00000 1.0000
2     2 0.00000 2.00000 2.0000 2.00000 2.00000 2.0000
3     3 0.00000 3.00000 3.0000 3.00000 3.00000 3.0000
4     4 0.00000 4.00000 4.0000 4.00000 4.00000 4.0000
5     5 0.00000 5.00000 5.0000 5.00000 5.00000 5.0000
6     1 0.11111 0.98537 1.0664 0.95703 0.80309 0.9408
7     2 0.11111 1.91233 2.0431 1.93546 1.76423 1.7954
8     3 0.11111 2.89180 3.1357 2.97548 3.04977 3.0097
9     4 0.11111 4.09118 4.0426 3.95294 4.02712 4.0887
10    5 0.11111 5.02453 4.8226 5.02239 5.07338 5.0010
..  ...     ...     ...    ...     ...     ...    ...
```

Should this become the default?

Also as suggested by @jennybc, we need a `.to = ".col"` option to set the name of these output columns.

**Comment by jennybc** [comment]
😊 row stuff. I have actually been trying rather hard, w/ precious little success, to use `purrr` to do useful things with list-columns. It feels really hard to glue things together row-wise. I haven't even convinced myself whether I should be fiddling with `purrr` or `dplyr`. I have this hope to expand or replace (mutate?) one list column in a data.frame with several new atomic vectors. They would come from row-binding a list-column of atomic vectors of common length or row-binding a few numbers you have extracted from a list-column of un-simple objects, like fitted models.

**Comment by lionel-** [comment]
Maybe this is a job for tidyr. I don't see clearly what you're trying to do but have you looked into `tidyr::unnest()`?

**Comment by hadley** [comment]
@jennybc for list-columns, I'm starting to think that purrr functions inside a mutate is most natural.
