### ISSUE TITLE
Bug in every and some for 

### ISSUE THREAD

**Issue by stefanfritsch** [hadley/purrr#114]
Hi,

The following line in both every and some,

    if (isTRUE(.p(.x[[i]], ...))) 

should be

    if (isTRUE(.f(.x[[i]], ...))) 

As it is right now it only works if `.p` is itself a function.

Tests:

    context("every-some")
    y <- list(0:10, 5.5)
    test_that(
      "every accepts formulas as predicates",
      expect_true(y %>% every(~is.numeric(.x))),
      expect_false(y %>% every(~is.integer(.x)))
    )

Ciao
Stefan

**Comment by lionel-** [comment]
Thanks Stefan,

It's already fixed in #96.
