### ISSUE TITLE
Can you compose() with try()?

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#117]
I want to map over rows of a data frame. Some errors are to be expected and it's problematic if I lose the return value for the rows which don't error (IRL I'm calling an API). I am trying and failing to use `compose()` with `try()`. The second attempt below is what I want. Is there some way to use `compose()` with `try()` to modify the function I'm mapping?

``` r
library(purrr)
library(dplyr)

z <- data_frame(base = c(2, exp(1), 10),
                x = list(letters[1:3], 2^(1:3), c(-1, 10, 100)))

z %>%
  map_n(logb)
#> Error in log(x, base): non-numeric argument to mathematical function

logb2 <- function(...) try(logb(...))
z %>% 
  map_n(logb2)
#> Warning in logb(...): NaNs produced
#> [[1]]
#> [1] "Error in log(x, base) : non-numeric argument to mathematical function\n"
#> attr(,"class")
#> [1] "try-error"
#> attr(,"condition")
#> <simpleError in log(x, base): non-numeric argument to mathematical function>
#> 
#> [[2]]
#> [1] 0.6931472 1.3862944 2.0794415
#> 
#> [[3]]
#> [1] NaN   1   2

## can something like this work?
logb3 <- compose(try, logb)
z %>%
  map_n(logb3)
#> Error in log(x, base): non-numeric argument to mathematical function
```

**Comment by lionel-** [comment]
That's not possible because `compose()` will first execute `logb()` and then feed the result to `try()`. But the error already occurred back then.

This could be avoided if `compose()` created a new call of the type `c(b(a(...)))` instead of of evaluating the calls sequentially in a for loop. But this would require some special evaluation and Hadley wants purrr to be a "standard evaluation zone" ;)

**Comment by lionel-** [comment]
more generally, the functional way of handling errors is with monads, but monadic programming is not straightforward and probably not worth the trouble in R.

**Comment by hadley** [comment]
Or of course you could do:

```R
z %>% 
  map_n(~ try(logb2(.)))
```

Maybe we need to pull over `plyr::failwith()`?:

```R
z %>% map(failwith(NULL, log2))
```

**Comment by lionel-** [comment]
Maybe `maybe()`?
```r
x %>% map(maybe(log2, otherwise = NULL))
```

**Comment by hadley** [comment]
Yeah, maybe ;)

**Comment by jennybc** [comment]
Call me ☎️.

Wouldn't you want the error message that `try()` saves for you most of the time, though?

**Comment by lionel-** [comment]
it could save the error message when `otherwise` is `missing()`.

Also I think it should be quiet by default. This is purrrer this way because that's one less side effect.

**Comment by hadley** [comment]
Moved to #120
