### ISSUE TITLE
C++ implementations of map, map2, map3 etc?

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#118]
Advantages:

* Control exactly what happens
* Speed? (need to benchmark)
* Build in output type (logical, integer, double, character, list) at low level

**Comment by hadley** [comment]
The implementation of `lapply()` is https://github.com/wch/r-source/blob/b156e3a711967f58131e23c1b1dc1ea90e2f0c43/src/main/apply.c#L34 - rather than doing the subsetting in C, it creates a new variable called `i` in the enclosing scope, then constructs and evaluates a call to `f(x[[i]], ...)`.

Very rough start on C++ implementation:

```R
// [[Rcpp::export]]
List map(List x, Function f, Environment e) {
  int n = x.length();
  List out(n);

  SEXP tmp = PROTECT(LCONS(R_Bracket2Symbol,
    LCONS(X, LCONS(isym, R_NilValue))));
  SEXP R_fcall = PROTECT(LCONS(FUN,
    LCONS(tmp, LCONS(R_DotsSymbol, R_NilValue))));

  for (int i = 0; i < n; ++i) {
    e.assign("i", i);


  }

  return out;
}
```

**Comment by lionel-** [comment]
That's also the strategy I used in rows-based functions. See `by_slice_impl()` and `by_row_impl()` in https://github.com/hadley/purrr/blob/6d57a81302eaa18579f82b414b6bbbc9e6ca282e/src/rows.cpp#L186. Maybe we can use the same call constructor in all mapping functions.

**Comment by hadley** [comment]
@lionel- oh nice - that's going to save me a lot of struggling!

**Comment by lionel-** [comment]
that's not guaranteed ;)
