### ISSUE TITLE
Move predicates into own package

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#124]
Since they're useful in many places

@gaborcsardi do you already have a mini package for predicates? In purrr, we have:

``` r
is_atomic <- function(x) {
  typeof(x) %in% c("logical", "integer", "double", "complex", "character", "raw")
}
is_vector <- function(x) {
  is_atomic(x) || is.list(x)
}
is_bare_list <- function(x) {
  !is.object(x) && is_list(x)
}
```

etc

**Comment by gaborcsardi** [comment]
Micropackage. :) Not yet. But happy to have one. :)

We just want them to return TRUE/FALSE? I often find it useful if they can also return an error message.

**Comment by smbache** [comment]
+1

**Comment by smbache** [comment]
I think true / false is best (more generally applicable). But perhaps as attribute.

**Comment by gaborcsardi** [comment]
Btw. there are already **a lot** of assertions in the assertive.* packages, e.g. http://www.r-pkg.org/pkg/assertive.numbers

**Comment by jennybc** [comment]
@gaborcsardi: following that link made me realize that 14 of the 16 `assertive.*` packages don't seem to be in the METACRAN mirror?

https://github.com/search?q=user%3Acran+assertive&type=Repositories

**Comment by lionel-** [comment]
Instead of a micro-package, do we need a "standard lib" package with underscored function names and sane behaviours? This would be a good home for `set_names()` (#119) etc. Could be called `lowliner` ;)

**Comment by smbache** [comment]
Or if only for predicates, "`predrcats`" ;-)

**Comment by smbache** [comment]
With a cat hex logo

**Comment by gaborcsardi** [comment]
@jennybc yeah, the GitHub mirroring is not working now, I'll fix it soon.

**Comment by hadley** [comment]
I do like predrcats!

**Comment by imanuelcostigan** [comment]
Is there a reason why `is_na` is not available ? I am happy to help transport these predicates to a separate package if help is needed.

**Comment by smbache** [comment]
@imanuelcostigan `is_na %>% is_na`

**Comment by imanuelcostigan** [comment]
@smbache ?

**Comment by smbache** [comment]
Just found it amusing that you point out that `is_na` is not available (i.e. `is_na`)... :-)

**Comment by imanuelcostigan** [comment]
ok LOLz

**Comment by imanuelcostigan** [comment]
@lionel- i have been also been thinking that something like that would be sweet. 

Been reading [Swift's API design guidelines](https://swift.org/documentation/api-design-guidelines/) (ugh...camelCase) and reflecting on the lack of design principles in R's core packages (not just camelCase vs snake_case). That isn't surprising given its genesis.

**Comment by imanuelcostigan** [comment]
Starting [`predrcats` package](https://github.com/imanuelcostigan/predrcats)

**Comment by hadley** [comment]
Will be moving into rlang
