### ISSUE TITLE
Need more control over simplification in zip_n()

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#126]
Maybe `.simplify` should be a list giving the expect types of the atomic vectors? That way we can throw an error if it's not the expected type? 

I think that also implies we need `flatten_int()`, `flatten_dbl()`, `flatten_chr()` and `flatten_lgl()`.

**Comment by hadley** [comment]
@lionel- what do you think about eliminating the `.simplify` argument and instead have a `simplify()` function?

**Comment by lionel-** [comment]
I like to have the .simplify argument inside `transpose()` because the simplify operation is required for symmetry, as with this example:

```{r}
list(x = rbernoulli(100), y = 1:100) %>%
  transpose() %>%
  map_if("x", ~ update_list(., y = ~ y * 100)) %>%
  transpose(.simplify = TRUE)
```

But maybe what we need is a vector version:
```{r}
is_transposed_vlist <- function(.x) {
  every(.x, is_list) && all(every(.x, every, is_scalar_atomic))
}

transpose_v <- function(.x) {
  if (!(every(.x, is_atomic) || is_transposed_vlist(.x))) {
    stop("components are neither atomic vectors nor lists of atomic vectors",
      call. = FALSE)
  }
  out <- transpose(.x)
  map(out, simplify_if_possible)
}

# List of vectors is round-tripped
list(x = letters, y = 1:26) %>%
  transpose_v() %>%
  transpose_v() %>%
  str()

# Fails
list(x = letters, y = 1:26, z = as.list(letters)) %>%
  transpose_v() %>%
  str()
```


It'd be nice to export `simplify()` but we need to figure out a good naming pattern to reflect the relationship with `as_vector()` which is currently defined like this:

```{r}
as_vector <- function(.x, .type) {
  if (can_simplify(.x, .type)) {
    unlist(.x)
  } else {
    stop("Cannot coerce .x to a vector", call. = FALSE)
  }
}
```

Maybe `as_vector()` and the plural `as_vectors()`? Or should `as_vector()` be linked to `flatten()` family and become something like `flatten_v()`?

**Comment by hadley** [comment]
I don't think `transpose()` needs to be symmetric here. It's the same basic behaviour as `map(1:5, identity)` - i.e. as a convenience, purrr functions allow any vector when technical you should need a list. So `transpose(list(1:3, 4:6))` is just short hand for `transpose(list(as.list(1:3), as.list(4:6)))`.

The thing I don't like about `transpose_v()` is that it's not type-stable - you don't know for sure what sort of object will come out. I'd rather restrict that behaviour to a single function (e.g. `simplify()`). 

Maybe we could have `simplify_v()` and `simplify()`?

**Comment by lionel-** [comment]
Good points.

> Maybe we could have simplify_v() and simplify()?

Or `simplify()` and `simplify_all()`, the latter referring to the list components? This would be consistent with functions such as `all_equal()` and `all_identical()`.
