### ISSUE TITLE
idea: trigger / elicit / when

### ISSUE THREAD

**Issue by smbache** [hadley/purrr#13]
I've though about a way to have some sort of "pattern matching" / advanced "if-else" construct for use in pipelines. In F# you have brilliant pattern matching, but the idea is not really portable, I think.

I did however make a function that I find quite useful; not sure where it belongs though. Perhaps here, but maybe it is too NSE for lowliner. 

So far I've named it `trigger`, as it triggers an action associated with the first valid match / condition. Another name could be `elicit`, or even just `when`. Each condition-action pair is specified as a formula: `condition ~ action`. If `isTRUE(condition)` the corresponding action is evaluated and returned. Names can be assigned using named arguments (and will be available to both conditions and actions) and the value being matched can be referred to as the dot.

Here's a gist: https://gist.github.com/smbache/afe0e1e105a8f56eb83f

and here's how it can be used (simple examples):

```R
1:10 %>% 
  trigger(
    sum(.) <=  50 ~ sum(.),
    sum(.) <= 100 ~ sum(.)/2,
    sum(.)/3   # With no condition it will always be true, acts as default.
  )
   
1:10 %>% 
  trigger(
    sum(.) <=   x ~ sum(.),
    sum(.) <= 2*x ~ sum(.)/2,
    0,
    x = 60
  )            
   
iris %>% 
  subset(Sepal.Length > 10) %>%
  trigger(
    nrow(.) > 0 ~ .,
    iris %>% head(10)
  )
```

**Comment by holstius** [comment]
+1 for `when()` !

(Why not `where()`, to be friendly to the SQL-folk? Too many `where`s in other namespaces, like `pryr::where`?)

**Comment by hadley** [comment]
I think this is now rendered moot by `case_when()` in dplyr
