### ISSUE TITLE
map_lgl should .f instead of .p

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#134]
@lionel- what do you think? I think it's better to be consistent within this group of functions, rather providing useful additional behaviour that requires more explanation.

**Comment by lionel-** [comment]
hmm yes it made more sense when it was a single `probe()` function.

**Comment by lionel-** [comment]
A side effect is that now `map_if()`, `keep()` etc don't work with logical vectors. So we should probably reinstate `probe()` for internal use.

**Comment by hadley** [comment]
And we clearly need some unit tests for those possibilities too

**Comment by lionel-** [comment]
yup I'll do it.
