### ISSUE TITLE
flatten_*() and NAs

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#137]
I get that the `flatten_*()` functions are type specific. Would a possible exception be made for logical `NA`? If someone, like say me, forgets or can't make sure that `NA`s are of the proper type, would coercion make sense?

``` r
library(purrr)
flatten_chr(list('A', NA))
#> Error in flatten_chr(list("A", NA)): Element 2 is not a character (logical)
flatten_chr(list('A', NA_character_))
#> [1] "A" NA
```

**Comment by hadley** [comment]
I think probably the flatten and map functions need to automatically upcast (ie. logical -> integer -> double -> character) to avoid this hassle.  It's not hard, just fiddly in C.
