### ISSUE TITLE
Negate needs an adverb-y name

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#139]

**Comment by tjmahr** [comment]
negating?

`negating(str_detect)(letters, c("a", "b"))`

**Comment by hadley** [comment]
A few more ideas:

* `negatively()`
* `conversely()`
* `anti()`
* `contrarily()`
* `reversed()`
* `backwards()`

**Comment by smbache** [comment]
* opposing()

**Comment by smbache** [comment]
* opposing?

**Comment by tjmahr** [comment]
oppositely

On Dec 16, 2015, at 4:35 PM, Stefan Milton Bache <notifications@github.com<mailto:notifications@github.com>> wrote:


  *   opposing?

-

**Comment by lionel-** [comment]
Personally I think function operators should be verbs. The way I see it, adverbs should be functionals taking some data and a function (the verb) and returning data.

**Comment by hadley** [comment]
This no longer seems so important to me; `negate()` feels natural.
