### ISSUE TITLE
unzip may cause scoping problems when lowliner is loaded

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#14]
e.g.:

```
install_github("klutometis/roxygen")
## Downloading github repo klutometis/roxygen@master
## Error in unzip(src, list = TRUE) : unused argument (list = TRUE)
```

I will PR a fix for devtools, but I assume this issue will popup in many other places.

Ultimately, it's the packages' responsibility to make sure they use unzip from the utils namespace, but I just thought you should be aware of this.

**Comment by lionel-** [comment]
a way out would be to rename `zip()` to `zip_n()` since it takes a list and operates on its elements, much like `map_n()` and `cross_n()`. Then we could also have `zip2()` and `zip3()` for consistency with other functions.

As for `unzip()`, it could be removed altogether since zipping is its own inverse operation. And name handling should be integrated in `zip()` (currently only `unzip()` handles names).

**Comment by hadley** [comment]
* `zip_n()` seems reasonable to me

* `zip_2(x, y)` would be equivalent to `zip_n(list(x, y))` right?

* Not sure how I missed that zip and unzip do the same thing :/.  Looks like unzip currently does better at maintaining names

* Do you want to do a PR?

**Comment by lionel-** [comment]
> zip_2(x, y) would be equivalent to zip_n(list(x, y)) right?

right.

> Do you want to do a PR?

When is the release due?

**Comment by hadley** [comment]
devtools is due this Friday, I'm teaching/traveling next week, so Sep 25? The release process should be pretty easy since there aren't any revdeps to break ;)

**Comment by lionel-** [comment]
yes I can have a look at this before sep 25.

**Comment by lionel-** [comment]
Then we should also rename `cross()` to `cross2()` to be consistent.

The would be that when a functions takes two or three lists, it should be suffixed with its "list-arity".

**Comment by hadley** [comment]
Sounds like a good idea!
