### ISSUE TITLE
head_while , tail_while unexpected behavior

### ISSUE THREAD

**Issue by marcoblume** [hadley/purrr#140]
Hi,

big <- function(x) x > 100
head_while(0:10, big)
tail_while(0:10, big)

Both return integer(0) , which seems to me does not make much sense in an example intended to explain how the functions are supposed to work.

The first example 

pos <- function(x) x >= 0
head_while(5:-5, pos)
tail_while(5:-5, negate(pos))

Makes more sense as an example.

Apologize if the first example works as intended.

Regards,

Marco

**Comment by hadley** [comment]
That example is to illustrate what happens when the predicate returns false for all values of `x`
