### ISSUE TITLE
mapping with named argument

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#141]
I want to use map but my input must be supplied to the `.f` function with a name. Position matching will never work.

My example is `gh::gh()`, which substitutes arbitrary named arguments into a template from a GitHub API endpoint. I tried to think of a more mundane example but could not, so maybe this is a hyper-specific problem?

``` r
#install_github("gaborscardi/gh")
suppressPackageStartupMessages(library(dplyr))
library(purrr)
library(gh)

repo <- c("dplyr", "purrr")
iss_list <- repo %>% 
  map(gh, endpoint = "/repos/hadley/:repo/issues", .limit = 4)
#> condition in .f(.x[[i]], ...): GitHub API error: 404 Not Found
#>   Not Found
```

But if I put `repo` into a data frame and use `pmap()` it works:

``` r
iss_list <- data_frame(repo  = repo) %>% 
  pmap(gh, endpoint = "/repos/hadley/:repo/issues", .limit = 4)
iss_list %>% 
  map(length)
#> [[1]]
#> [1] 4
#> 
#> [[2]]
#> [1] 4
```

Is there a way to do this w/o creating a temporary data frame?

**Comment by hadley** [comment]
I think pmap is probably the right solution here

**Comment by hadley** [comment]
You could also use ~ to create an anonymous function

**Comment by jennybc** [comment]
OK so yes this works too.

``` r
iss_list <- repo %>% 
  map(~ gh(repo = .x, endpoint = "/repos/hadley/:repo/issues", .limit = 4))
```
