### ISSUE TITLE
Can't install purrr from source on CentOS

### ISSUE THREAD

**Issue by MarcinKosinski** [hadley/purrr#146]
I am trying to install `purrr` package under CentOS, since this is a dependency in [`dplyr.spark.hive`](https://github.com/piccolbo/dplyr.spark.hive) package.

I can't install this package from the source downloaded from CRAN. I've described this issue on this [SO question](http://stackoverflow.com/questions/34134786/cant-install-r-package-from-source-under-centos). Could you please have a look at the error that is produced? Maybe it would be more meaningful for you :)

**Comment by lionel-** [comment]
Hi,

It looks like you have an old version of dplyr installed.

**Comment by MarcinKosinski** [comment]
Wow, thanks for fast reply. 
I'll try with the newest version.

**Comment by lionel-** [comment]
The package manager should now warn about this.

**Comment by MarcinKosinski** [comment]
Great, thanks it worked.
