### ISSUE TITLE
Using invoke() when signature doesn't match data

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#148]
I have a use case where I have a list of parameters that can't be directly used with `invoke()`. The list contains additional data and its names don't necessarily correspond to the invoked function.

We could handle this by providing a `.params` argument with which we can match function parameters to data names, and where we can specify unused data.
```r
invoke <- function(.f, .x = NULL, ..., .params = NULL) {
  if (!is.null(.params)) {
    .x <- connect_params(.x, .params)
  }
  do.call(.f, c(.x, list(...)))
}

connect_params <- function(x, params) {
  # Remove null-marked params
  nulls <- names(keep(params, is.null))
  x <- x[!(names(x) %in% nulls)]

  # Rename x according to new params
  common_x <- names(x) %in% names(params)
  common_p <- names(params) %in% names(x)
  old_names <- names(x)[common_x]
  p_names <- names(params)[common_p]

  match_pos <- map_int(p_names, match, old_names)
  new_names <- params[common_p][match_pos]
  names(x)[common_x] <- new_names

  x
}
```

Example:
```r
x <- list(
  list(lambda = 1, sd = 2, sim = 1),
  list(lambda = 2, sd = 2, sim = 1),
  list(lambda = 3, sd = 2, sim = 2),
  list(lambda = 4, sd = 2, sim = 2)
)

params <- list(lambda = "mean", sim = NULL)
invoke_map(list(rnorm), x, n = 1, .params = params)
```

I think it'd be better than modifying the data each time.

**Comment by lionel-** [comment]
by the way, would you be ok with wrapping `.f` in a list automatically in `invoke_map()`? It would be a bit less verbose when only one function is invoked.

**Comment by lionel-** [comment]
maybe `.params = NA` could wrap `.f` in a dotted lambda, so that arguments would match by position. Like the `.unname` argument in the composition helpers (would need to merge the two interfaces then)

**Comment by hadley** [comment]
Hmmm, in that case I'd prefer to explicitly modify the list:

```R
x %>% 
  map(~ list(mean = .$lambda, sd = .$sd)) %>% 
  invoke_map(list(rnorm), ., n = 1)
```

Then it's easier to check if the transformation has happened correctly.

I think it's reasonable for `invoke_map(rnorm)` to work the same way as `invoke_map("rnorm")`, but I'd rather do it with an explicit test for `is.function()`.
