### ISSUE TITLE
Calling lists of functions

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#150]
I have a use case where I need to call a list of functions but `invoke_map()` isn't completely adequate.

```{r}
funs <- list(
  . %>% select(cyl),
  . %>% select(am)
)

funs %>% invoke_map(list(list(mtcars)))
funs %>% invoke_map(list(NULL), mtcars)
```

I find the first form non intuitive and the second one a bit inelegant. Should we have a new invoking verb where `.x` is hard coded to `list(NULL)`? Or maybe this should be outside the scope of the invoke family:

```{r}
run <- function(.f, ...) .f(...)

funs %>% map(run, mtcars)
```

or:

```{r}
run <- function(.f, ...) {
  if (is_list(.f)) {
    map(.f, run, ...)
  } else {
    .f(...)
  }
}

funs %>% run(mtcars)
```

**Comment by lionel-** [comment]
Instead of the last form, maybe it should be `run()` and `run_map()` to mirror the invoking functions.

**Comment by lionel-** [comment]
I wonder if we could have a `.pure` switch in functions like `run_map()` or `invoke_map()` that would memoise the calls when `TRUE`.

**Comment by hadley** [comment]
Three more options:

```R
funs %>% invoke_map(value = mtcars)
funs %>% map(invoke, value = mtcars)
funs %>% map(~ .(mtcars))
```

**Comment by lionel-** [comment]
nice, but the `value = ` trick won't work in other situations. For example with memoised pipelines, or functions modified with `partial()`, etc.

The last one works but I like `run_map()` better I think because of the symmetry with `invoke_map()`.

**Comment by hadley** [comment]
Oh, I missed yet another option: 

```R
funs %>% invoke_map(, mtcars)
```

**Comment by lionel-** [comment]
I didn't know that would work, this one is nice :)

do you like the idea of a `.pure` or `.memoise` argument?

**Comment by hadley** [comment]
It seems most natural as an adverb to me (and there's already `memoise::memoise`)
