### ISSUE TITLE
Name-based predicates

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#152]
Would there ever be predicate functions that consult the names? I.e. relatives of the name-based helpers for `dplyr::select()`. So `nm_starts_with()`,  `nm_contains()`, `nm_matches()`, etc.

Imagine you want to convert the iris width measurements from cm to in. Various ways are already possible:

``` r
library(dplyr)
library(purrr)

iris2 <- iris
iris2[grep("Width", names(iris2))] <- 
  iris2[grep("Width", names(iris2))] %>% 
  map(~ . * 0.4)  
iris2 %>% head(2)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         1.4          1.4        0.08  setosa
#> 2          4.9         1.2          1.4        0.08  setosa

iris %>% 
  map_at(grep("Width", names(.)), ~ . * 0.4) %>%
  head(2)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         1.4          1.4        0.08  setosa
#> 2          4.9         1.2          1.4        0.08  setosa
```

But this would be even nicer:

``` r
## fiction but would be nice
iris2 <- iris %>% 
  map_if(nm_matches("Width"), ~ . * 0.4)
```

The ability to select on name seems to live only in `dplyr` whereas the ability to conditionally map based on other stuff seems to live only here in `purrr`.

Some `dplyr` issues re: more flexibility for selecting and mutating: https://github.com/hadley/dplyr/issues/1569, https://github.com/hadley/dplyr/issues/1501, https://github.com/hadley/dplyr/issues/1229, https://github.com/hadley/dplyr/issues/497.

**Comment by hafen** [comment]
+1

It would be nice in general to be able to access the name of the element when inside a map.  It could be made available as `.nm` or `nm()` or something.

**Comment by davharris** [comment]
+1

Is `grep` and `[` still the best way to do this for now?

**Comment by hadley** [comment]
Some of this is solved in <https://github.com/paulponcet/lplyr>

**Comment by hadley** [comment]
In order for this to work:

```R
iris2 <- iris %>% 
  map_if(nm_matches("Width"), ~ . * 0.4)
```

We'd need some way to tell `nm_matches()` what the current names are. This sort of scoping feels very different to the rest of purrr so I don't think it belongs here. However, I am thinking of eventually pulling the `select_vars()` stuff out of dplyr, and into its own package as it is useful in many other places.

**Comment by hadley** [comment]
(I also like the idea of using the `nm_` prefix)
