### ISSUE TITLE
flatten and names

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#157]
It's really easy to lose names with `flatten()`. Is there some design reason it must be this way?

Here's an example of creating a flat list from `...` where the `unlist()` behaviour is more desirable.

``` r
library(purrr)

jfun_unlist <- function(...) as.list(unlist(list(...)))
jfun_unlist(list(a1 = "a_one", a2 = "a_two"), b = "b")
#> $a1
#> [1] "a_one"
#> 
#> $a2
#> [1] "a_two"
#> 
#> $b
#> [1] "b"
```

Why does b lose its name?

``` r
jfun_flatten <- function(...) as.list(flatten(list(...)))
jfun_flatten(list(a1 = "a_one", a2 = "a_two"), b = "b")
#> $a1
#> [1] "a_one"
#> 
#> $a2
#> [1] "a_two"
#> 
#> [[3]]
#> [1] "b"
```

**Comment by hadley** [comment]
It's preserving the names of the elements of a, but there are no elements in b. Compare these two:

``` r
list(list(a1 = "a1", a2 = "a1"), b = "b") %>% flatten() %>% 
    str()
#> List of 3
#>  $ a1: chr "a1"
#>  $ a2: chr "a1"
#>  $   : chr "b"
list(list(a1 = "a1", a2 = "a1"), c(b = "b")) %>% flatten() %>% 
    str()
#> List of 3
#>  $ a1: chr "a1"
#>  $ a2: chr "a1"
#>  $ b : chr "b"
```

I think the behaviour is currently principled (i.e. always copy names from one level down), but might not be that useful. What do you think the following code should return?

```R
list(a = list(a1 = "a1", a2 = "a1")) %>% flatten() %>% str()
list(a = list("a1", "a1")) %>% flatten() %>% str()
list(a = 1, b = 2) %>% flatten() %>% str()
```

(I think the principle might be if an element is a single unnamed component, you should copy the name one level down)

**Comment by jennybc** [comment]
I think this is what I would hope for:

``` r
#list(a = list(a1 = "a1", a2 = "a1")) %>% flatten()
list(a1 = "a1", a2 = "a1")

#list(a = list("a1", "a1")) %>% flatten()
list("a1", "a1")

#list(a = 1, b = 2) %>% flatten()
list(a = 1, b = 2)
# this is the only one that differs from current behaviour?
```

**Comment by hadley** [comment]
That last example should probably be

```R
list(a = list(1), b = list(2)) %>% flatten()
```

But I think the same principle applies - i.e. if the element has length one, and is unnamed, use the top-level name. I'll see if I can make that work.

**Comment by hadley** [comment]
@jennybc I think this is right, but can you confirm that this matches your intuition:

```R
  out <- flatten(list(a = list(x = 1), b = list(y = 2)))
  expect_equal(out, list(x = 1, y = 2))
```

**Comment by jennybc** [comment]
Yes this seems very natural. Thanks for the change.
