### ISSUE TITLE
GCC failure

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#160]
From CRAN: "This seems to fail on my Debian GCC based check systems, with"

```
* checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  14: test_that("empty", {    empty <- function(...) numeric(0)    rows_collation <- invoke_rows(empty, mtcars[1:2], .collate = "rows")    cols_collation <- invoke_rows(empty, mtcars[1:2], .collate = "cols")    list_collation <- invoke_rows(empty, mtcars[1:2], .collate = "list")    expect_equal(rows_collation$.out, numeric(0))    expect_equal(cols_collation$.out, numeric(0))    expect_equal(list_collation$.out, rerun(32, numeric(0)))    expect_equal(dim(rows_collation), c(0, 3))    expect_equal(dim(cols_collation), c(0, 3))    expect_equal(dim(list_collation), c(32, 3))})
  15: eval(expr, envir, enclos)
  16: eval(exprs, envir)
  17: sys.source2(fname, new.env(parent = env))
  18: FUN(X[[i]], ...)
  19: lapply(paths, test_file, env = env, reporter = current_reporter,     start_end_reporter = FALSE)
  20: test_files(paths, reporter = reporter, env = env, ...)
  21: test_dir(test_path, reporter = reporter, env = env, filter = filter,     ...)
  22: with_top_env(env, {    test_dir(test_path, reporter = reporter, env = env, filter = filter,         ...)})
  23: run_tests(package, test_path, filter, reporter, ...)
  24: test_check("purrr")
  aborting ...
  Segmentation fault
```

@lionel- I think this is your code :/

**Comment by lionel-** [comment]
oh :/

can this wait until next week? I have a deadline Monday. I guess I'll have to learn how to use Valgrind for that one.

**Comment by hadley** [comment]
Yeah, by the end of next week would be fine. It's only on GCC unfortunately :/

**Comment by lionel-** [comment]
on my machine, GCC fails with optimisation level `-O2` or higher. This happens in dplyr's data frame visitors code. So we could always use tidyr's nesting approach with `do()` as a workaround. Will try to investigate further for a fix.

Now I've noticed that Travis sometimes infloops while testing the rows functions. This happens randomly but always in the same test snippet and dplyr is not involved. Will explore further as well.

**Comment by lionel-** [comment]
Should be good now.

Seems like a bug in GCC. Passing an object by reference twice would trigger the crash, only with GCC on `-O2` or `-O3` optimisation. Creating an intermediary copy (no big deal as it's a SEXP) fixes this.

The random infloop should be fixed as well.

**Comment by hadley** [comment]
Are you sure this isn't a `PROTECT()` bug with dplyr?

**Comment by lionel-** [comment]
hmm didn't think about that, I'll check it again. But wouldn't a PROTECT bug be triggered with all compilers and all optimisation levels? And wouldn't it be nondeterministic?

**Comment by hadley** [comment]
Yeah, I think that's the case.
