### ISSUE TITLE
by_row / when non-list collation

### ISSUE THREAD

**Issue by ajay-d** [hadley/purrr#162]
Using `when` with no default gives an odd result if I try to collate the columns.  Maybe it should error out?

```R
library(purrr)

mtcars %>%
  by_row(when, .$hp < 100 ~ 'small',
               .$hp < 200 ~ 'medium',
               .$hp < 300 ~ 'large', 
         .collate = 'rows', .to = 'newVar')
```

**Comment by lionel-** [comment]
hmm no, it's a bug occurring when one of the result is `NULL` (here because you didn't give a default for rows that don't match a pattern).

I'll look into it thanks. And that's a nice combination of `by_row()` and `when()` by the way :)
