### ISSUE TITLE
transpose() on invalid data should result in error, not warning

### ISSUE THREAD

**Issue by huftis** [hadley/purrr#164]
As discussed at http://blog.rstudio.org/2016/01/06/purrr-0-2-0/#comment-20462 running `transpose()` on lists of non-conforming dimensions should result in an error, not a warning.

Currently, the following leads to an empty `$error` element (and a `$result` element where the `z` data in the original object has disappeared):

```
x = rerun(5, x = runif(1), y = runif(5))
x[[4]]$z = 3:5
safely(transpose)(x)
```

**Comment by hadley** [comment]
This is a worse case of the same basic problem:

``` r
library(purrr)

transpose(list(
  list(x = 1, y = 2),
  list(y = 2, x = 1)
))
#> $x
#> $x[[1]]
#> [1] 1
#> 
#> $x[[2]]
#> [1] 2
#> 
#> 
#> $y
#> $y[[1]]
#> [1] 2
#> 
#> $y[[2]]
#> [1] 1
```
