### ISSUE TITLE
Reporting from safely()

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#171]
OK this is superpicky. But you seem to have a policy of suppressing the call in most error messages ...

Could the errors captured by `safely()` refer to the actual function I gave it? Or maybe not talk about `.f(...)`?

``` r
library(gh)
library(purrr)

ghsafe <- purrr::safely(gh::gh)
res <- ghsafe(endpoint = "/user", .token = "wut")
res
#> $result
#> NULL
#> 
#> $error
#> <condition in .f(...): GitHub API error: 401 Unauthorized
#>   Bad credentials
#> >
conditionCall(res$error)
#> .f(...)
```

**Comment by hadley** [comment]
It's really hard unfortunately - this is why I use `.call = FALSE` by default
