### ISSUE TITLE
purrr package failed for dplyr

### ISSUE THREAD

**Issue by abiyug** [hadley/purrr#172]
While trying to install purrr package on Ubuntu 14.04 LTS. I get the following error

 make: *** [dplyr.o] Error 4
**ERROR: compilation failed for package ‘dplyr’**

 the full error is below.

#########################
install.packages("purrr")
<snip>
```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [dplyr.o] Error 4
ERROR: compilation failed for package ‘dplyr’
* removing ‘/home/antex/R/x86_64-pc-linux-gnu-library/3.2/dplyr’
Warning in install.packages :
  installation of package ‘dplyr’ had non-zero exit status
ERROR: dependency ‘dplyr’ is not available for package ‘purrr’
* removing ‘/home/antex/R/x86_64-pc-linux-gnu-library/3.2/purrr’
Warning in install.packages :
  installation of package ‘purrr’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmptsu2B9/downloaded_packag
```
########################
RStudio IDE:
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.1 LTS

> Sys.info()
                                      sysname                                       release 
                                      "Linux"                                         "3.13.0-32-generic" 
                                      version                                         nodename 
"#57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014"          "ubuntu" 
                                      machine                                        login 
                                     "x86_64"                                        "unknown" 
                                         user                                           effective_user 
                             

#######################
Ubuntu version
`Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by lionel-** [comment]
A google search suggests you don't have enough memory to compile dplyr. Maybe compiling with clang will work better. To compile with clang, install it and modify `~/.R/Makevars` with
```makefile
CC	= clang
CXX = clang++
```

**Comment by abiyug** [comment]
Yea that was it!  Increased the memory (it is virtual environment) - that fixed the issue.

Perhaps returning a warning message suggesting "minimum  x memory is required to install this packages."  can be helpful, instead of the current ominus sounding

```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
```

Here is the successful output after the memory increase.
```
installing to /home/antex/R/x86_64-pc-linux-gnu-library/3.2/purrr/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (purrr)

```

**Comment by lionel-** [comment]
Great, thanks
