### ISSUE TITLE
every() and NAs

### ISSUE THREAD

**Issue by kablag** [hadley/purrr#174]
I'm very impressed by purrr but from my point of view it's strange result:
`every(NA, function(x) x > 0)`
`[1] FALSE`
Doesn't it break R rules about NA?
Maybe it's better to return NA like all()?
`all(c(NA) > 0)`
`[1] NA`

**Comment by lionel-** [comment]
hmm yes, we should probably return `NA` if one element of `.x` is `NA`. And with `some()`, we should do the same except if one element is `TRUE`.

**Comment by hadley** [comment]
``` r
library(purrr)
every(NA, ~ .x > 0)
#> [1] FALSE
```
