### ISSUE TITLE
Feature Request: pattern matching

### ISSUE THREAD

**Issue by mplourde** [hadley/purrr#185]
Perhaps you've already considered this, but I often find myself wanting to perform pattern-matching-like operations to extract elements from lists, such as you might do in Scala or Python, e.g:

```{R}
L1 <- list(1:2, 3:4)
.(a, b) := L1
a
# [1] 1 2
b
# [1] 3 4

L2 <- list(5:6, 7:8, 9:10)
.(a, b) := L2
a
# [1] 5 6
b
# [[1]]
# [1] 7 8
# [[2]]
# [1]  9 10
```

Would you ever consider making functionality like this available in **purrr**? 

Thanks for creating such a great extension to R's functional dialect. Like **ggplot2** and **dplyr/tidyr**, it's completely changed the way I write R and helped me advocate the usage of this language to skeptical colleagues. 

(Here's the definition of `:=` used above)

```{R}
library(dplyr)
`:=` <- function(e1, e2, env=parent.frame()) {
    e <- substitute(e1) %>% tail(-1)
    for (i in seq_along(e)) {
        name <- e[[i]] %>% as.character()

        e2_longer <- length(e2) > length(e) 
        at_last <- i == length(e)
        value <- if (e2_longer & at_last) tail(e2, -i+1) else e2[[i]]

        assign(name, value, env=env)
    }
}
```

**Comment by hadley** [comment]
(I'd call this destructuring bind rather than pattern matching, which to me is more about finding the right function to apply)

I've thought about this a bit, and I basically think that it's out of scope for purrr - it changes assignment too much, and while it's a cool idea (and lovely in other languages) it just doesn't feel "R" like to me

**Comment by smbache** [comment]
Also R CMD check would fail to recognize the names ex post... And all kinds of trouble would follow...
