### ISSUE TITLE
For S4 objects, character indexing should use slots

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#200]
e.g. https://twitter.com/expersso/status/733220790557155328

**Comment by peterchristofferholm** [comment]
I can't seem to access S4-object slots through character indexing directly in `map_*`. However, it works as intended with pluck. AFAIK the selection in map is powered by pluck so it seems weird that it does not work. See reprex:

s4_obj <- setClass(
  "test object",
  slots = c(first_slot = "numeric",
            second_slot = "logical"),
  
  prototype = list(first_slot = 1:10,
                   second_slot = TRUE)
)
example <- s4_obj()
example
#> An object of class "test object"
#> Slot "first_slot":
#>  [1]  1  2  3  4  5  6  7  8  9 10
#> 
#> Slot "second_slot":
#> [1] TRUE
example %>% map("first_slot")
#> Error: `.x` is not a vector (S4)
example %>% pluck("first_slot")
#>  [1]  1  2  3  4  5  6  7  8  9 10

**Comment by hadley** [comment]
You need to put the object in order for it to work with map.
