### ISSUE TITLE
Feature request: Debugging

### ISSUE THREAD

**Issue by kendonB** [hadley/purrr#208]
Currently this doesn't seem to play very nice with standard debugging tools. For example, I can only see as low as the ``mutate_impl`` call when using ``mutate(foo = data %>% map(foo2))`` with ``options(error = recover)``. Using ``browser()`` isn't very helpful as it can require many continues before finding the actual bug.

**Comment by hadley** [comment]
I don't think there's anything we can do about that unfortunately.
