### ISSUE TITLE
`cumulate()` ?

### ISSUE THREAD

**Issue by steromano** [hadley/purrr#209]
Similar to `accumulate()`, but taking a function that accepts a vector (`mean`, `median`, etc) and applying it cumulatively over a vector, e.g.

```
> cumulate(median, 1:10)
 [1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5
```

**Comment by hadley** [comment]
This feels out of scope for purrr. vctrs will provide cumulative versions of all important summary functions.
