### ISSUE TITLE
Dispersion parameter for quasipoisson model

### ISSUE THREAD

**Issue by hstrosn** [hadley/purrr#215]
I'm using map to apply a quasipoisson model as a function across age group and health outcome following the steps laid out in this talk: Hadley Wickham: Managing many models with R. Everything works great except the dispersion parameter isn't contained in the summary model information. I've figured out not so tidy ways to get out which primarily means running the model twice. Once to extract all the information neatly using broom and once to extract dispersion. Is there anyway to add the dispersion parameter to the summary model information for easy extraction?

**Comment by hadley** [comment]
I don't think this is related to purrr. A better place to ask would be a mailing list or stackoverflow
