### ISSUE TITLE
purrr:contains and dplyr::contains is likely to cause confusion

### ISSUE THREAD

**Issue by sebastiansauer** [hadley/purrr#217]
Both `purrr` and `dplyr` have a contains() function, but with different syntax.

For example, if I load dplyr first, and purr afterwards, it will bite me:

```
   library(dplyr)
   library(purrr)
   data(tips, package = "reshape2")
   tips %>% select(contains("total"))
   ## Error in .p(.x[[i]], ...) : argument ".y" is missing, with no default
```

May it would be helpful to disambiguate the two functions?

**Comment by hadley** [comment]
@lionel- any thoughts on a better name? We might need to consider more prefixes for purrr functions since it's going to be loaded increasingly commonly

**Comment by lionel-** [comment]
we could prefix with `vec_` secondary functions that operate on vectors, generic and atomic? But then what would be the prefix for atomic vectors functions?

**Comment by hadley** [comment]
`atm_`?  But if you think of `contains()` as a function that operates on vectors, maybe it should go in vctrs? I think we'll need to figure out what goes where.

**Comment by lionel-** [comment]
this makes me think that the tidyverse is starting to look like Emacs lisp functions ;) Elisp doesn't have namespaces so all function names have to be prefixed.

>  maybe it should go in vctrs?

I'm not sure, this is a wrapper around `some()`. We'll also have to figure out what should be the dependency graph of those packages.

> atm_?

ah nice, I was stuck with `ato_` for some reason.

**Comment by mexindian** [comment]
Or just change one of the verbs to `has()`?

**Comment by jtr13** [comment]
Yes, confusion caused.
> select(x100, contains("P"))
Error in .p(.x[[i]], ...) : argument ".y" is missing, with no default

**Comment by hadley** [comment]
And similarly for `order_by()`

**Comment by kleinschmidt** [comment]
Why did `sort_by` need to be removed as well, and what's the recommended replacement (other than "use tibbles")?
