### ISSUE TITLE
map_df() input names affect shape of return value 

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#222]
If I provide an unnamed list as input to `map_df()`, I get the data frame I expect: one row per element of input.

The same list, if it has names, produces a data frame that is transposed. So one column per input element. Why did I name it? To make it more easily navigable in an list-viewing htmlwidget (the real example is much bigger!)

I suppose this just another example of https://github.com/hadley/dplyr/issues/1676, although I don't feel like I've run into this specifically before.

``` r
library(purrr)

x <- list(
  list(login = "mickey",
       public_repos = 27),
  list(login = "minnie",
       public_repos = 88)
)

x %>% 
  map_df(`[`, c("login", "public_repos"))
#> # A tibble: 2 x 2
#>    login public_repos
#>    <chr>        <dbl>
#> 1 mickey           27
#> 2 minnie           88

x %>% 
  set_names(c("mickey", "minnie")) %>% 
  map_df(`[`, c("login", "public_repos"))
#> # A tibble: 2 x 2
#>      mickey    minnie
#>      <list>    <list>
#> 1 <chr [1]> <chr [1]>
#> 2 <dbl [1]> <dbl [1]>
```

**Comment by swLai** [comment]
x %>% 
  set_names(c("mickey", "minnie"))

**Comment by vspinu** [comment]
Here is another example - mapping on a named object binds by columns instead of rows, and mapping on unnamed objects throws an error:

```R
> map_df(c(a = "a", b = "b"), ~ c(a = 1, b = 2))
# A tibble: 2 x 2
      a     b
  <dbl> <dbl>
1     1     1
2     2     2
> map_df(c("a", "b"), ~ c(a = 1, b = 2))
Error: cannot convert object to a data frame
> 
```

**Comment by hadley** [comment]
The root causes is `bind_rows()` so I've moved the issue to dplyr
