### ISSUE TITLE
by_row appends columns w/ same name rather than overwriting

### ISSUE THREAD

**Issue by mwillumz** [hadley/purrr#225]
I'm just curious whether this is intended. See the below code which results in a nested tibble with two columns named 'filtered'

```
data(iris)

Data <- group_by(iris, Species) %>%
  nest()

Data <- by_row(Data, function(x){
  unnest(x) %>%
  filter(Sepal.Length > 5)
}, .to = 'filtered')

by_row(Data, function(x){
  unnest(x, filtered, .sep = "-") 
}, .to = 'filtered')

```

**Comment by lionel-** [comment]
It probably should overwrite the column, but all those row-based functions are going to be deprecated soon in favour of the new `mutate/summarise_all()`, `_at()` and `if()` family of functions in dplyr.

Also it's recommended to use a combination of `mutate()` and `map()` to perform rowwise operations. For example you'd do

```r
Data <- group_by(iris, Species) %>%
  nest() %>%
  mutate(
    filtered = map(data, . %>% filter(Sepal.Length > 5))
  )
```

which is nicer in a way.
