### ISSUE TITLE
filtering by date within map() is throwing an error

### ISSUE THREAD

**Issue by mwillumz** [hadley/purrr#227]
In transitioning from by_row() to map() approach I've found that filtering by date does not appear to be working within map(). 

```
library(nycflights13)
data(weather)
Data <- mutate(weather, date = as.Date(time_hour)) %>%
  select(origin, date, temp) %>%
  group_by(origin) %>%
  nest() 

# I can filter on numeric
mutate(Data, filtered = map(data, . %>% filter(temp >= 90)))
# But I can't filter on dates
mutate(Data, filtered = map(data, . %>% filter(date >= '2013-07-01')))
  
# However filtering on dates does work outside of the map function:
filter(Data$data[[1]], date >= '2013-07-01')
```

**Comment by mwillumz** [comment]
I just realized that if I use a var name other than 'date' it'll work. Presumably it's clashing with a function somehow.

**Comment by lionel-** [comment]
This would be an issue to report in the dplyr repo. However I think that updating dplyr will fix your problem as I can't reproduce.
