### ISSUE TITLE
zip() doesn't play well with factors and named vectors

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#23]
`zip()` has some limitations with list of vectors.

* It coerces factors to numeric
* It forgets the names of the vector elements

A solution to the first problem is to use `[[` instead of `.subset2()`. This could be decided by testing for factors, so we still get the performance benefit of `.subset2`.

One solution to the second problem may be to offer a `.soft_subset` argument which would cause zip to defer the subsetting to `[` or `.subset()`. This is possibly related to the ideas in https://gist.github.com/hadley/8667699

Here is a possible implementation of `zip()` that would play better with vectors:

```
zip2 <- function(.x, soft_subset = FALSE) {
  n <- unique(map_v(.x, length, .type = integer(1)))
  if (length(n) != 1) {
    stop("All elements must be same length", call. = FALSE)
  }

  # .subset and .subset2 do not handle factors
  # `[[` does not handle named vectors
  subset <- 
    if (soft_subset) {
      .subset
      ## base::`[`
    } else {
      base::`[[`
    }

  lapply(seq_len(n), function(i) {
    lapply(.x, subset, i)
  })
}


factors <- list(
  a = factor(1:2),
  b = factor(3:4)
)
named <- list(
  a = setNames(1:2, c("aa", "ab")),
  b = setNames(3:4, c("ba", "bb"))
)

zip(factors)
zip2(factors)

zip(named)
zip2(named, soft_subset = TRUE)
```

**Comment by hadley** [comment]
How does that compare performance-wise to just using `[`?

**Comment by lionel-** [comment]
Is it okay to coerce integers to doubles in `can_simplify()`? So that the following would work:

```r
list(x = rbernoulli(100), y = 1:100) %>%
  zip_n() %>%
  map_if("x", ~ update_list(., y = ~ y * 100)) %>%
  zip_n(.simplify = TRUE)
```

**Comment by hadley** [comment]
Yeah, that seems reasonable. I really need to write out the list of "safe" simplifications - it's a problem in dplyr too.

**Comment by hadley** [comment]
I think this is no longer an issue with the refined definition of `tranpose()` and the deprecation of `zip2()` and `zip3()`

**Comment by lionel-** [comment]
The issue is still there. I think overall purrr doesn't handle factors well. `by_slice()` discards attributes and factor levels (see #106) as does `transpose()`. Since factors are a basic R data structure I think we should support them, even if that means an ad hoc mechanism. But it'd be great to come up with something more general.
```r
factors <- list(
  a = factor(letters[1:2]),
  b = factor(letters[3:4])
)
transpose(factors) %>% str()
#> List of 2
#>  $ :List of 2
#>   ..$ a: int 1
#>   ..$ b: int 1
#>  $ :List of 2
#>   ..$ a: int 2
#>   ..$ b: int 2
```

**Comment by hadley** [comment]
The issue is no longer there because I've defined it away by saying that transpose only works with atomic vectors ;)  At some point we should consider whether we want to add support for important non-atomic vectors - factors, dates, and date times.
