### ISSUE TITLE
is_bare_list returns TRUE for a named list

### ISSUE THREAD

**Issue by jeremystan** [hadley/purrr#230]
The function `is_bare_list` returns `TRUE` for a list with names.

``` r
> is_bare_list(list(a = 1))
[1] TRUE
```

The documentation says that "bare objects have no class attributes" but names is an attribute.

**Comment by lionel-** [comment]
But names is not a class attribute ;) The `is_bare_` prefix is for checking if a data structure is an object.

**Comment by jeremystan** [comment]
Got it. My use case is for determining objects from arrays in the results of `jsonlite`. For example:

```{r}
> library(jsonlite)
> library(purrr)
> object <- fromJSON('{"key": "value"}', simplifyVector = FALSE)
> object
$key
[1] "value"

> array <- fromJSON('["value"]', simplifyVector = FALSE)
> array
[[1]]
[1] "value"

> object %>% is_bare_list
[1] TRUE
> array %>% is_bare_list
[1] TRUE
```

Perhaps the best answer is to export `has_names` as Hadley suggests, as that accomplishes what I am after:

```{r}
> purrr:::has_names(object)
[1] TRUE
> purrr:::has_names(array)
[1] FALSE
```

**Comment by jeremystan** [comment]
Maybe instead it should be a more general function, `has_attributes`, which can check for a specific set of attributes by name (such as "names").
