### ISSUE TITLE
map_* doesn't use .null when .f is a function

### ISSUE THREAD

**Issue by jeremystan** [hadley/purrr#233]
This is related to #231, which while fixed for the case where `.f` is a *character* vector, does not work when `.f` is a function:

```{r}
list(1L, NULL) %>% map_int(identity)
#> Error: Result 2 is not a length 1 atomic vector

list(1L, NULL) %>% map_int(identity, .null = NA)
#> Error in .f(.x[[i]], ...) : unused argument (.null = NA)
```

This is the workaround:

```{r}
list(1L, NULL) %>% map(`%||%`, NA) %>% map_int(identity)
#> [1]  1 NA
```

**Comment by hadley** [comment]
Yes, this is by design: `.null` only affects subsetting. If you're using a function, the expectation is that it will do the right thing (or you'll wrap it yourself)
