### ISSUE TITLE
map() with integer arguments shuold return error when the element doesn't exist

### ISSUE THREAD

**Issue by yutannihilation** [hadley/purrr#238]
The document says:

> If character or integer vector, e.g. `"y"`, it is converted to an extractor function, `function(x) x[["y"]]`. To index deeply into a nested list, use multiple values; `c("x", "y")` is equivalent to `z[["x"]][["y"]]`.

But, actually there is a difference. When trying to retrieve a nonexistent element, it throws a error with a function argument.

```r
library(purrr)
x <- list(list(1, 2), list(10, 20))

map(x, function(x) x[[3]])
#> Error in x[[3]] : subscript out of bounds
```

But when specifying integer instead of function as the argument, `map()` silently returns `NULL`.

```r
map(x, 3)
#> [[1]]
#> NULL
#> 
#> [[2]]
#> NULL
```

I'm a bit afraid that this behaviour may be bad when the position is specified by a variable like this:

```r
position <- 1
map(x, position)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 10
```

In R, it is a common mistake to assign an integer vector to the variable intended to be used as an integer scalar. But it won't return errors.

```r
position <- 1:2
map(x, position)
#> [[1]]
#> NULL
#> 
#> [[2]]
#> NULL
```

In my opinion, `map()` should stop with error when there are no element at the specified position.

**Comment by hadley** [comment]
This is a deliberate choice to make integer and character indexing consistent.
