### ISSUE TITLE
mapnm_*

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#240]
Would be useful to have 

``` R
mapn <- function(.x, .f, ...) {
  out <- map2(names(.x), .x, .f, ...)
  names(out) <- names(.x)
  out
}
```

For more complicated stuff it is better off to using a tribble + list-cols etc, but this is still a very useful pattern.

**Comment by lionel-** [comment]
+1,  I use this all the time. Never been able to find a satisfying name though. I've been thinking about something like `tagged_map()`, or `map2_nx()` to reflect the contents of the arguments. But `map2_nx_int()` etc don't look great.

To be consistent with `pmap()` should it be a prefix, eg `nmap()`?

**Comment by hadley** [comment]
Yeah, `nmap` might be best

**Comment by jennybc** [comment]
It feels like `map2(seq_along(.x), .x, .f, ...)` also comes up.

**Comment by hadley** [comment]
Maybe imap for that?

**Comment by lionel-** [comment]
Should we generalise the pattern?

```r
x %>% map_with(names, f)

x %>% map_lgl_with(seq_along, f)
```

**Comment by hadley** [comment]
Maaaaaybe, but the goal is to be shorter than `map2()`, so I think `names()` would have to be the default, which means that the argument would need to come later and usually be supplied by a named argument.

**Comment by lionel-** [comment]
hmm you're right, `map_with()` would be unnecessary jargon.

Perhaps we can combine the names and index mappers into one function, and have the `seq_along()` when the input is unnamed.

```r
x %>% imap(f)
unname(x) %>% imap(f)
```

**Comment by hadley** [comment]
Oh yeah, that makes sense

**Comment by lionel-** [comment]
For tilde-lambda's it'd be weird to have the index/names as `.x` and the input as `.y`. It would be nicer to have `.x` and `.i`.

**Comment by jennybc** [comment]
> Perhaps we can combine the names and index mappers into one function, and have the seq_along() when the input is unnamed.

That has the really nice property that it's what you would get if you used `tibble::enframe()` and took the list-cols approach @hadley alluded to at the very start.

**Comment by hadley** [comment]
I propose we call this family of functions `imap_*`, and define it something like this:

```R
index <- function(x) {
  names(x) %||% seq_along(x)
}

imap <- function(.x, .f, ...) {
  f <- as_function(.f, ..., .arg_names = c(".x", ".i"))
  map2(.x, index(.x), .f, ...)
}
```

(assuming some changes to `as_function()`)

I think it's more logical to pass the index as the second argument, which also naturally leads to preserving the names/indices of the first.

**Comment by hadley** [comment]
Decided to not customise the argument names; introducing another variant seems confusing.
