### ISSUE TITLE
Inconsistent behavior of map_df when using lists vs vectors

### ISSUE THREAD

**Issue by holgerbrandl** [hadley/purrr#241]
E.g in 
```
1:3       %>% map_df(~data_frame(x=1))
list(1:3) %>% map_df(~data_frame(x=1))
```
the vector as input results in a data.frame with 3 rows (as expected), but surprisingly the list-version returns a table with just a single row. 

According to the docs .x can be a list or an atomic vector, but somehow the results are different.

used version:  purrr_0.2.2

**Comment by lionel-** [comment]
That's because the list contains only one element whereas the vector contains 3 elements.
