### ISSUE TITLE
add depth_exists or similar

### ISSUE THREAD

**Issue by timelyportfolio** [hadley/purrr#242]
Often, I want to test if a depth exists, so something like this would be very helpful.  Thanks so much for purrr!

```
depth_exists <- function(l,depth){
  inherits(try(at_depth(l,depth,~NULL),silent=TRUE),"list")
}
```

**Comment by hadley** [comment]
I don't really understand what you mean by "if a depth exists"

**Comment by hadley** [comment]
Ok, now I see. Closing as duplicate of #243
