### ISSUE TITLE
as_function matches variables instead of functions

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#25]
When a function and a variable have the same name, all lowliner tools using `as_function()` will match the variable instead of the function.

To reproduce:
```
l <- list(a = 1:5, b = 6:10)
map(l, mean)

mean <- "  "
map(l, mean)

## Error in .subset2(g, f) (from utils.R#59) : subscript out of bounds
```

One way around this would be to do something like `match.fun()` to match the function in the calling environment using `get(fun_name, envir = calling_env, mode = "function")`.

But then there is the issue that the calling environment is not at a fixed number of steps in the calling hierarchy because `as_function()` is sometimes called from the mapping function itself, and sometimes from `find_selection()`.

The cleanest way to capture the calling environment is probably to use lazyeval in this way:
```
as_function <- function(f) {
  # Capture the calling environment and try to match a function (as opposed to a variable)
  lazy <- lazyeval::lazy(f)
  if (is.name(lazy$expr)) {
    f_name <- as.character(lazy$expr)
    maybe_f <- try(get(f_name, envir = lazy$env, mode = "function"),
      silent = TRUE)

    if (is.function(maybe_f)) {
      return(maybe_f)
    }
  }

  if (is.character(f) || is.numeric(f)) {
    function(g) .subset2(g, f)
  } else if (inherits(f, "formula")) {
    if (length(f) != 2) {
      stop("Formula must be one sided", call. = FALSE)
    }
    make_function(alist(. = ), f[[2]], environment(f))
  } else {
    stop("Don't know how to convert ", paste0(class(f), collapse = "/"),
      " into a function", call. = FALSE)
  }
}
```

But this currently does not work reliably because of the lazyload DB problem (see https://github.com/hadley/lazyeval/issues/18).

**Comment by hadley** [comment]
I think is just an inevitable part of the way that `as_function` works - I don't think it has a high risk of causing problem.
