### ISSUE TITLE
Add higher-order function that returns a function that evaluates in a new environment

### ISSUE THREAD

**Issue by kendonB** [hadley/purrr#250]
I have had trouble with functions that capture calling environments (`lm`, `ggplot`) capturing objects in the environment that aren't necessary for the call. This causes memory problems when pulling objects from a parallel cluster, and unnecessary disk usage when saving these objects.

The problem is demonstrated at [https://github.com/hadley/tidyr/issues/224].

A proposed solution is at [http://r.789695.n4.nabble.com/Model-object-when-generated-in-a-function-saves-entire-environment-when-saved-td4723192.html]. It proposes to evaluate the function in a new environment that has `.GlobalEnv` as its parent.

A more user friendly solution, based on the above, is proposed in [https://github.com/hadley/purrr/pull/221]. It proposes the `in_new_env` function which takes a function returns that function evaluated in a new environment, only with its own inputs exported to that environment.

The code for this function is:

```
in_new_env <- function(.f){
   function(...) {
     params <- list(...)
     env <- new.env(parent = globalenv())
     params <- lapply(params, function(x) {if (inherits(x,"formula")) {environment(x)<-env}; x})
     assign(".params.", params, envir = env)
     env$.f <- .f
     evalq(do.call(".f", .params.), envir=env)
   }
 }
```

**Comment by hadley** [comment]
This seems like a bad idea to me. We'll have more shortly on tidyeval, which should do more to resolve such issues.
