### ISSUE TITLE
pmap discards attributes

### ISSUE THREAD

**Issue by kendonB** [hadley/purrr#251]
Is this a feature or a bug?

```
seq(as.Date("1990-01-01"),
    as.Date("1990-01-02"), by = "days") %>% 
  list() %>% 
  purrr::pmap(function(x){
    print(class(x))
  })
# [1] "numeric"
# [1] "numeric"
# [[1]]
# [1] "numeric"
# 
# [[2]]
# [1] "numeric"
```

`purrr::map` yields a date object.

**Comment by picasa** [comment]
Apparently, it's the same for POSIXct class.

```
library(lubridate)
library(dplyr)
library(purrr)

# data frame containing model inputs
inputs <- data_frame(a=1, t0=ymd("2016-10-12"))

# simplified model function
model <- function(t0, ...) {return(data_frame(time=format(t0, format="%d/%m")))}

# direct call to model fonction : time is the expected character string
model(t0=ymd("2016-10-12"))$time

# wished call to model function : time is a numeric value encoded in character string
inputs %>% pmap_df(., model) %>% .$time
```

**Comment by lionel-** [comment]
It's a known non-feature that we will resolve with the vctrs package (we need C-level methods for joining vectors).

**Comment by shrektan** [comment]
bite by this issue as well...

**Comment by hadley** [comment]
This is a complicated issue and the root cause is not within purrr. We are aware of the problem and working to fix it in the long-term.

**Comment by Ax3man** [comment]
Factors are also coerced to numeric:

`pmap(list(1:5, factor(letters)[1:5]), paste)`

**Comment by Deleetdk** [comment]
Issue still here as of **purrr** 0.2.4. Ran into it while looping over some bioinf data. Unfortunately, one has to get to the very end of the list of chromosomes to get to the error (i.e. it occurs first at X after 22 of 24 parts complete).

**Comment by yutannihilation** [comment]
@Deleetdk FYI: the further discussion continues here.
https://github.com/tidyverse/purrr/issues/358#issuecomment-363091446
