### ISSUE TITLE
some precisions about the exact purpose of purr?

### ISSUE THREAD

**Issue by randomgambit** [hadley/purrr#252]
Hello everybody,

I am kind of new to R, coming from Stata (not even a proper language) and Python. I have to admit I have a hard time understanding what `purr` exactly does. 

Is it something for programmers only? I am a finance phd and I basically use `dplyr`, `data.table`, `tidyr` and others to reshape and merge datasets, and I essentially run linear models on my data. 

Can someone please tell me in one/two sentences what can `purr` do for me in that context? I **feel** `purr` may be very useful, but I cannot find any good tutorial/help/description that would apply to this context.

Thanks!

**Comment by randomgambit** [comment]
For instance, my understanding was that `purr` allowed for an efficient looping over the columns of a dataframe, but this link https://lionel-.github.io/2015/10/08/using-purrr-with-dplyr/ seems to suggest that `purr` is not anymore about dataframes. What to think?

**Comment by jennybc** [comment]
I have some rough [slides](https://jennybc.github.io/purrr-tutorial/slides.html) and [worked examples](https://jennybc.github.io/purrr-tutorial/examples.html) from a tutorial I gave this summer, in preparation for teaching I will do later this fall. It's not polished, but will perhaps help you figure how purrr might be useful to you.

**Comment by randomgambit** [comment]
thanks!
