### ISSUE TITLE
Turning named vectors into data.frame/tibble

### ISSUE THREAD

**Issue by rentrop** [hadley/purrr#255]
FEATURE REQUEST (hope that purrr is the right place for this)

Following up on [this](http://stackoverflow.com/questions/40036207/tidyverse-prefered-way-to-turn-a-named-vector-into-a-data-frame-tibble) SO question: 

A shortcut for turning named vectors into data.frame/tibble would be great:
For me a common task is to turn named vectors into data.frames. `bind_rows` and `map_df` do not handle this nicely. So you can do one of the following workarounds:

```
require(tidyverse)
vec <- c("a" = 1, "b" = 2)
# Version one
vec %>% enframe %>% spread(name, value)
# Version two
vec %>% t %>% as_tibble
```

A usecase in a `purrr` setting: (this is why i put the feature-request as a purrr issue)

```
require(tidyverse)
require(rvest)
txt <- c('<node a="1" b="2"></node>',
         '<node a="1" c="3"></node>')

txt %>% map(read_xml) %>% map(xml_attrs) %>% map_df(~t(.) %>% as_tibble)
```

Which gives you:

```
# A tibble: 2 × 3
      a     b     c
  <chr> <chr> <chr>
1     1     2  <NA>
2     1  <NA>     3
```

**Comment by lionel-** [comment]
I think this is https://github.com/hadley/dplyr/issues/1676

**Comment by jennybc** [comment]
This XML example comes up for me frequently 👍.

**Comment by rentrop** [comment]
One more case where it woule be handy:
[](http://stackoverflow.com/questions/40801342/fast-split-of-xml-document-into-data-frames-by-xpath-expression/40801799#40801799)

**Comment by hadley** [comment]
Can you file this in tibble please?
