### ISSUE TITLE
slice_rows executes column names as code

### ISSUE THREAD

**Issue by davharris** [hadley/purrr#257]
I initially discovered this because I had a column name with a space in it:

```
x = mtcars
colnames(x) = paste(colnames(x), 1:ncol(x))
slice_rows(x, 1)

# Error in parse(text = x) : <text>:1:5: unexpected numeric constant
# 1: mpg 1
```

After I looked at the traceback information, I found that purrr was actually using lazyeval to parse and run the column names as code.  That seems unsafe to me (analogous to SQL injection, but possibly worse because R can call `system`).

**Comment by lionel-** [comment]
this is dplyr's `group_by()`. Could you post over there please.

**Comment by davharris** [comment]
Will do.

**Comment by hadley** [comment]
@lionel- are you sure `slice_rows()` shouldn't be calling `lapply(x, as.name)`?

**Comment by lionel-** [comment]
Hmm I thought this wasn't necessary since the nse versions of dplyr verbs accept string-quoted code.

**Comment by davharris** [comment]
@hadley Thanks for taking this seriously.

**Comment by hadley** [comment]
I think the semantics for `group_by` are wrong for the use case here - `group_by()` parses, rather than coercing to names.

**Comment by lionel-** [comment]
Changed in last commit.

**Comment by davharris** [comment]
Thanks @lionel-!
