### ISSUE TITLE
Compose does unexpected things

### ISSUE THREAD

**Issue by darrkj** [hadley/purrr#260]
These may bot be bugs but they seem to not do what I would expect.

```r
library(purrr)

# This will create a function or fseq
df <- . %>% range %>% diff

# It works as expected.
1:10 %>% df

# If I want to use compose to add something after this it fails, which may be okay since
# you could just use another pipe.
1:10 %>% compose(sign, df)

# But this was where things seemed weird, this does work. Just added the parens
1:10 %>% (compose(sign, df))

# And this will work as well.
new_fn <- compose(sign, df)
1:10 %>% new_fn

# To see why this was happening I tried to add compose in the initial sequence.
fn <- . %>% range %>% diff %>% compose(sign, .)

# And then this fails.
1:10 %>% fn

# The above may be fine, I was thinking it was something related to how compose uses
# match.fun and some differences between an actual function class and one that is fseq.
# But then I would expect this not to work if that was true, but it does.
fn <- compose(sign, . %>% range %>% diff)
1:10 %>% fn
```

Maybe I should not be doing this anyway but it still seems strange.

**Comment by lionel-** [comment]
If you want to pipe to a function returned by another function, you should add another pair of parentheses:

```r
1:10 %>% compose(sign, df)()
```

Otherwise you're really doing:

```r
compose(1:10, sign, df)
```

instead of

```r
compose(sign, df)(1:10)
```

More generally, it helps to always add the trailing parentheses when using magrittr to avoid this kind of confusion: `x %>% range() %>% diff()`

**Comment by smbache** [comment]
Adding parens to RHS, e.g `lhs %>% (rhs)` forces the evaluation of rhs before labs is piped along and is expected magrittr behavior.

**Comment by lionel-** [comment]
some people prefer trailing parentheses and others like Stefan don't like them, so you have to chose a side ;)

**Comment by smbache** [comment]
But trailing parens will not help if rhs is call-generating.. not so common, but still ;)

**Comment by smbache** [comment]
As in 

```R
some_call <- ...
lhs %>% (some_call)
```
