### ISSUE TITLE
Walk doesn't work with rm

### ISSUE THREAD

**Issue by cfhammill** [hadley/purrr#262]
I was trying to clean up my environment by filtering some objects and piping them to `walk(rm)`,
I later remembered `rm(list = ., envir = .GlobalEnv)` works, but I'm a bit surprised the original approach didn't work. 

reprex:

```
a <- b <- 5
walk(c("a", "b"), rm)
```

The error is 

```
Error in .f(.x[[i]], ...) : ... must contain names or character strings
```

Which suggests `...` is being bound strangely, it should be empty. Could it have something to do
with `rm` taking `...` as its first argument?

**Comment by lionel-** [comment]
That's more of a bug in `rm()`. Could you file an issue upstream please?

```r
a <- 1
rm(letters[[1]])
```

**Comment by cfhammill** [comment]
Sure thing, thanks Lionel

**Comment by lionel-** [comment]
though on hindsight I think they won't consider it a bug because they want people to be able to do

```r
a <- 1
rm(a)
```

But arguably if `rm()` is called with a complex expression it makes sense to check if it evaluates to a string or quoted symbol.

@hadley maybe we should provide a standard evaluation version of `rm()` in rlang?

**Comment by cfhammill** [comment]
I'll report it anyway just in case.

**Comment by hadley** [comment]
It's not a bug in `rm()`, it's working as designed:

```R
a <- b <- 5
rm(c("a", "b"))
rm(list = c("a", "b"))
```

**Comment by cfhammill** [comment]
@hadley I don't think it does work as intended, `letters[[1]]` evaluates to a single element character vector, `rm(letters[[1]])` should be the same as `rm("a")` no?

**Comment by hadley** [comment]
No. Because the first argument is special.
