### ISSUE TITLE
Output structure inconsistency between dmap, dmap_if, dmap_at

### ISSUE THREAD

**Issue by rsuhada** [hadley/purrr#263]
I'm bit confused about the output of `dmap_if` / `dmap_at` vs. `dmap` and their `map*` counterparts.

Example - calculating column wise sums on mtcars:
```R
    mtcars %>% dmap(sum)
```
yields what I'd expect:

>  mpg   cyl   disp    hp   drat      wt   qsec    vs    am  gear  carb
>  <dbl> <dbl>  <dbl> <dbl>  <dbl>   <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
> 1 642.9   198 7383.1  4694 115.09 102.952 571.16    14    13   118    90

However both:
```R
    mtcars %>% dmap_if(is.numeric, sum)
    mtcars %>% dmap_at(1:ncol(mtcars), sum)
```
yield data frames with one row for each input row with the sums correct, but repeating

> mpg cyl   disp   hp   drat      wt   qsec vs am gear carb
> Mazda RX4           642.9 198 7383.1 4694 115.09 102.952 571.16 14 13  118   90
> Mazda RX4 Wag       642.9 198 7383.1 4694 115.09 102.952 571.16 14 13  118   90
> ...

Is this the intended behaviour?

Using map* yields same results always (consistent with dmap)

    mtcars %>% map(sum)
    mtcars %>% map_if(is.numeric, sum)
    mtcars %>% map_at(1:ncol(mtcars), sum)

Thank you very much!

**Comment by lionel-** [comment]
Hello,

This is why we have deprecated those functions in favour of dplyr's new family of colwise mutate and summarise. The distinction between mutating and summarising operations allows a consistent output in those situations:

```r
mtcars %>% mutate_if(is.numeric, sum)
mtcars %>% summarise_if(is.numeric, sum)
```
