### ISSUE TITLE
Caught in between `flatten()` and `unnest()`

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#265]
I have a tibble with two variables, an atomic vector of names (repositories) and a list column of lists of objects (issues). Am I missing a better way to remove one level of hierarchy from the list column, while maintaining the link to the names?

``` r
suppressPackageStartupMessages(library(tidyverse))
#> Conflicts with tidy packages ----------------------------------------------
library(gh)

idf <- tibble(repo = c("svglite", "babynames"))
idf <- idf %>%
  mutate(issues = repo %>% map(~ gh("/repos/hadley/:repo/issues", repo = .x)))
lengths(idf$issues)
#> [1] 2 6
```

I want a tibble with 2 + 6 = 8 rows, one per issue, and 2 variables, repo and issues. I'd like to `unnest()` but issues consists of neither atomic vectors nor data frames.

``` r
idf %>% 
  unnest(issues)
#> Error: Each column must either be a list of vectors or a list of data frames [issues]
```

`flatten()` does what I want to `idf$issues` but does not replicate `repo`.

``` r
idf %>% 
  mutate(issues = flatten(issues))
#> Error: wrong result size (8), expected 2 or 1
```

Does this just have to be done "by hand"?

``` r
tibble(
  repo = rep(idf$repo, lengths(idf$issues)),
  issues = flatten(idf$issues)
)
#> # A tibble: 8 × 2
#>        repo      issues
#>       <chr>      <list>
#> 1   svglite <list [21]>
#> 2   svglite <list [21]>
#> 3 babynames <list [22]>
#> 4 babynames <list [22]>
#> 5 babynames <list [21]>
#> 6 babynames <list [21]>
#> 7 babynames <list [22]>
#> 8 babynames <list [21]>
```

**Comment by hadley** [comment]
Maybe this just requires teaching `unnest()` about lists?

**Comment by hadley** [comment]
Moved to tidyr. In the future, may want to draw explicit connections between `flatten()` and `unnest()`
