### ISSUE TITLE
does update_list_  exist, or can we have it?

### ISSUE THREAD

**Issue by bbolker** [hadley/purrr#267]
Use case:

```
x <- list(a=1,b=2)
y <- list(b=3,c=4)
update_list_(x,.dots=y)
## result: list(a=1,b=3,c=4)
```

(don't think I have the power to tag this with [wishlist])

**Comment by lionel-** [comment]
This could be an additional `.values` argument to `update_list()`.

**Comment by bbolker** [comment]
I've now realized this is basically just `utils::modifyList`, which I'm happy enough with, but it does still feel like it would be a useful thing to include in the tidyverse.

**Comment by hadley** [comment]
We'll fix this as part of a general review of ... and splicing

**Comment by hadley** [comment]
See #287 for more
