### ISSUE TITLE
transposed list "constructor"?

### ISSUE THREAD

**Issue by smbache** [hadley/purrr#268]
Would it make sense to include a function for constructing transposed lists, e.g. 

```R
tlist <- function(...)
{
   transpose(list(...))
}
```
So that rather than writing 

```R
transpose(list(foo, bar, baz))
```
one can write

```R
tlist(foo, bar, baz)
```

**Comment by hadley** [comment]
Hmmm, could you provide a use case?

**Comment by smbache** [comment]
Well, there are just a few js libraries that expect data in this transposed form, e.g. [this highcharts example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/scatter/). It's not necessary, but I've made it myself a few times, to avoid repeated `transpose(list(...))` calls...

**Comment by hadley** [comment]
This just feels a bit too specific to me.  I'll keep thinking about it though.

**Comment by lionel-** [comment]
linked to the `transposing()` idea in https://github.com/hadley/purrr/issues/256.
