### ISSUE TITLE
confusion re: `map` with grouped data frames

### ISSUE THREAD

**Issue by davharris** [hadley/purrr#269]
The documentation for `map` says

>Note that \code{map()} understands data frames, including grouped
data frames. It can be much faster than
\code{\link[dplyr:summarise_each]{mutate_each()}} when your data frame has many
columns. However, \code{map()} will be slower for the more common case of many
groups with functions that dplyr knows how to translate to C++.

I don't know what this means.

* Prior to reading this note, I expected `map` to simply apply the function to each column.

* However, the statement that `map` "understands" grouped data frames and that it can be used instead of `summarize_each` made me think it operated on groups instead of columns.

As of v0.2.2, it looks like `map` behaves like I initially expected (operating by column rather than by slice).

Perhaps the documentation could be updated to clarify the relationship between `map` functions with grouping?

```
library(tidyverse)
by_species <- iris %>% group_by(Species)

# returns a 3x5 tibble with each measurement's mean value for each species
by_species %>% mutate_each(funs(mean))

# returns a list with one mean for each column (including an NA for the 
# "species" column, because character vectors can't be averaged).
by_species %>% map(mean)

# Ungrouping does not change the results of `map`
by_species %>% ungroup() %>% map(mean)
```

**Comment by hadley** [comment]
Weird, that must be a left over from a long time ago
