### ISSUE TITLE
please don't kill by_slice 

### ISSUE THREAD

**Issue by davharris** [hadley/purrr#270]
I'd consider myself a relatively savvy tidyverse user, and it took me a very long time to figure out how to use the alternatives listed `by_slice`'s deprecation warning or in the NEWS file. The solutions I came up with are also inferior to `by_slice` in my opinion. I think it's valuable to have a higher-order function that understands dplyr's groupings.

Let's say I run the first example from `?by_slice`

```
library(tidyverse)
mtcars %>%
  slice_rows("cyl") %>%
  by_slice(partial(lm, mpg ~ disp))
```

I get the new deprecation warning: 

```
by_slice() is deprecated. Please use the new colwise family in dplyr.
E.g., summarise_all(), mutate_all(), etc.
```

`summarize_all` and friends don't seem to accomplish the same thing as `by_slice` at all, though.  I don't want to fit a linear model to each column, I want to fit one to each slice.

Eventually, I stumbled on the NEWS file, which suggests a combination of functions from three different tidyverse packages: `tidyr::nest()`, then `tidyr::nest()`, then `purrr::map()`. After more fumbling around than I'd like to admit to, I eventually got this to work. But it's complicated and ugly because it involves a longer pipeline and more nested function calls.

```
mtcars %>%
  slice_rows("cyl") %>%
  nest() %>% 
  mutate(.out = map(.$data, partial(lm, mpg ~ disp)))
```

Alternatively, I could use `do` for these examples, but `do` uses expressions rather than functions and requires an extra step for many common operations because it doesn't have an equivalent of `.collate`.

```
mtcars %>%
  slice_rows("cyl") %>%
  do(.out = partial(lm, mpg ~ disp)(.))
```

If `by_slice` has to go from `purrr`, please consider moving it to dplyr. At the very least, I think I'm not the only one that would benefit from more complete documentation for the alternatives.

**Comment by davharris** [comment]
(I just removed the emoji from the title because I realized it could be obnoxious if it showed up in lots of email subject lines etc.)

**Comment by lionel-** [comment]
oh, I liked seeing the emoji in my github emails ;)

**Comment by alistaire47** [comment]
+1. I can do the same thing with `do` (which is more confusing and less powerful) or list columns and reshaping (which takes a lot more code), but the collation abilities of `by_slice` and `by_row` are by far the cleanest way to add columns/rows programmatically. 

Admittedly the API is a little complicated, but the capabilities are too valuable to lose. Maybe `do` could gain a `.collate` parameter as part of a top-down overhaul, but till then these are worthwhile functions.

**Comment by lionel-** [comment]
FWIW dplyr may gain variants of verbs that operate in the direction of columns.

**Comment by alistaire47** [comment]
Good! Right now, these operations are [easier with `aggregate` than dplyr](http://stackoverflow.com/a/42153360/4497050).

**Comment by hadley** [comment]
I'd recommend filing an issue in dplyr, as this is now out of scope for purrr.  

I think the list-column approach does require a little more upfront investment, but it scales to more complicated scenarios more readily. @alistaire47 I don't think the tidyverse approach always needs to be shorter than the base R approach, but it should generally grow with you better.

**Comment by davharris** [comment]
For anyone that finds this page via search engine, `by_slice` has been moved to the [purrrlyr](https://github.com/hadley/purrrlyr) package.
