### ISSUE TITLE
Memory problem printing nested data frame in Studio notebook

### ISSUE THREAD

**Issue by wolfemd** [hadley/purrr#279]
Hi Hadley,

I've been using Rstudio Markdown Notebooks increasingly. I've also been learning to use everything in the "tidyverse", especially purrr functions to really make analysis in R a joy. I discovered a bug recently. 

I did e.g. 
nested_df <- group_by(Trait, Location) %>% nest() %>% mutate(Model=map(some_function)). 

The result is a nested data frame with model outputs stored in a new Model column. Before processing further.I printed "nested_df" to the screen in my Notebook. This gives a preview of the result so I can decide what to do next.

The problem happens if I save the Rmd with the preview of the nested_df on screen. Knitr goes crazy when it tries to update the ____.nb.html. The intermediate files it makes are huge (hundreds of Mb) and the "pandoc" process eats up _all_ of my RAM until I force it to quit. 

I'm not sure whether this is an Markdown, Knitr, or a Purrr/Tidy problem. Basically, I think Knitr doesn't know how to represent just the preview of the nested_df in the ___.nb.html file. It means I have to be exceedingly careful when using the combo of Markdown Notebook and Purrr.

Thanks!

**Comment by hadley** [comment]
This sounds like a knitr issue to me, given that tibble print correctly. I'd recommend filing a minimal reprex at the knitr repo.
