### ISSUE TITLE
Preserving map

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#28]
It would be great if lowliner had a mapping function that uses preserving subsetting as in this gist: https://gist.github.com/hadley/8667699

One difficult aspect is to create an interface that makes it easy to work with both the list component `x[[i]]`  and the (I'll call it like that for lack of a better idea) list frame `x[i]`. In your gist, you supply the list frame to the mapped function. I experimented with an alternative approach in which I supplied the list component instead, as is usual in mapping tools, along with a new placeholder referring to the list frame.

This new placeholder is called `..`. Since the double dot evokes the action of going one level up in a file hierarchy, I figured it would work well to represent the list frame. It is implemented as an active binding so that any modification to the list component is reflected in `..`.

Example:
```
test <- list(a = list(1, 2), b = list(3, 4))

out <- remap(test, function(x) {
  if (names(..) == "a") {
    rep(.., 2) %>%
      set_names(c("a1", "a2"))
  } else {
    x <- list(5)
    names(..) <- "B"
    ..
  }
})

str(out)

## List of 3
## $ a1:List of 2
##  ..$ : num 1
##  ..$ : num 2
## $ a2:List of 2
##  ..$ : num 1
##  ..$ : num 2
## $ B :List of 1
##  ..$ : num 5

```

The code is in https://gist.github.com/lionel-/12350ba7e583e9c10163

**Comment by hadley** [comment]
The use of a placeholder feels too magical to me - when reading the code, you'll need to remember where `..` comes from and how it's defined.

**Comment by lionel-** [comment]
It also does not feel very functional. Magrittr's placeholder is a shortcut for an input that has an explicit definition in the function signature. But the `..` placeholder creates a new implicit input.

Plus I can envision the special evalution implementing this placeholder to break in all sorts of ways.

**Comment by lionel-** [comment]
I encountered a good use case for preserving maps. It shows that it's definitely more useful to pass a list, `x[i]`, rather than an element, `x[[i]]`. It's easier to see this with functions that work on data frames.

The use case is to create disjunctive tables from factors to produce a design matrix prior to modelling. Here are some tools to do that:

```{r}
disjoin <- function(x, ...) {
  UseMethod("disjoin")
}

disjoin.default <- function(x, ...) {
  x <- as.factor(x)
  out <- lapply(levels(x), function(level) {
    as.numeric(x == level)
  })
  names(out) <- levels(x)
  dplyr::as_data_frame(out)
}

disjoin.data.frame <- function(df, sep = "_", ...) {
  if (length(df) == 0) {
    return(df)
  }

  out <- lapply(df, disjoin.default)
  n <- vapply(out, length, numeric(1)) %>% sum()
  out <- map2(out, names(out), function(var, name) {
    names(var) <- paste(name, names(var), sep = sep)
    var
  })

  out %>% dplyr::bind_cols() %>% tbl_df()
}
```

```{r}
mtcars[c("cyl", "am")] %>% disjoin()
## Source: local data frame [32 x 5]
##
##    cyl_4 cyl_6 cyl_8 am_0 am_1
## 1      0     1     0    0    1
## 2      0     1     0    0    1
## 3      1     0     0    0    1
## 4      0     1     0    1    0
## 5      0     0     1    1    0
## 6      0     1     0    1    0
## 7      0     0     1    1    0
## 8      1     0     0    1    0
## 9      1     0     0    1    0
## 10     0     1     0    1    0
## ..   ...   ...   ...  ...  ...
```

`disjoin()`'s default method takes an atomic vector and turns it into a data frame with `nlevels` columns. The columns are named after the levels. The data frame is probably easier to work with because it takes and returns the same type of data: data frames. It expands each column of the input data frame, and uses both the original column name and the factor levels to compose the names of its output. So the data frame version of `disjoin()` is in itself a mapping tool that applies the vector version on each `x[i]`. But, by the same token, it also works well (albeit redundantly) with a preserving version of `map()`.

In this case it made more sense for `disjoin()` to preserve-map the data frame on its own, but more generally we can imagine tools that only work with a one-column data frame, or that operate globally on all input columns rather than taking each one in turn. I think this kind of tools would be a prime use case for a preserving version of `map()`: functions that take a data frame column and may return a larger data frames.

By comparison, the `..` placeholder interface which introduces a new syntax via NSE would not be that general. It may be ok for programming with inlined lambda's, but functions relying on `..` would be basically useless on their own. So yeah, it really was not that good an idea.
