### ISSUE TITLE
General dots splicing tool

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#287]
```r
dots_list <- function(...) {
  dots <- list(...)
  
  needs_splat <- vapply(dots, "inherits", "splat", FUN.VALUE = logical(1))
  ind <- which(needs_splat)
  
  for (i in rev(ind)) {
    dots <- append(dots[-i], dots[[i]], after = i - 1)
  }
  
  dots
}


splat <- function(x) {
  stopifnot(is.list(x))
  class(x) <- c("splat", class(x))
  x
}

x <- list(3, 4)
dots_list(1, 2, splat(x))
```

* Needs more efficient implementation (creating output list then fill)
* Need to think about names

**Comment by hadley** [comment]
Could be implemented via predicate to `splice()`. See #61.

**Comment by hadley** [comment]
And it needs to be applied to all functions that take ... in purrr.

**Comment by hadley** [comment]
@lionel- are we now thinking this will be implemented in rlang?

**Comment by lionel-** [comment]
Yes I'm thinking on working on it this week.

**Comment by hadley** [comment]
Closing, since it'll be moved to rlang. I'm assuming you'll need a little C for the implementation.
