### ISSUE TITLE
Better documentation for pmap + formula incompatibility

### ISSUE THREAD

**Issue by tiernanmartin** [hadley/purrr#289]
While `pmap` accepts anonymous functions in  `.f` just like the other `map*`s, it doesn't allow users to make use of formulas (`~`).

I spent a while (probably too long) trying to glean this from `?map2`, only to eventually find the answer [here](http://stackoverflow.com/questions/41865159/r-purrrpmap-how-to-refer-to-input-arguments-by-name).

Please consider making this incompatibility explicit in the documentation - thanks!

**Comment by lionel-** [comment]
@hadley I still think it would be elegant to support positional `..1`, `..2`, `..3` etc in anonymous functions for these cases ;)

**Comment by hadley** [comment]
That seems reasonable. Would the numeric suffixes work everywhere? (so you'd have the choice between `.`, `.x`, and `..1`?  Maybe it should just be `.1` for consistency?

**Comment by lionel-** [comment]
Yes it would work everywhere. The `..1` approach has an elegant implementation: https://github.com/hadley/purrr/issues/63

**Comment by lionel-** [comment]
though of course I now found the use of `lazyeval::interp()` disgraceful. But the following works :)

```r
function(..., . = ..1, .x = ..1, .y = ..2)
```

**Comment by hadley** [comment]
Yeah, let's take a look again when you're working on purrr

**Comment by lionel-** [comment]
this is now rlang territory, I'll send a PR.
