### ISSUE TITLE
Description not complete

### ISSUE THREAD

**Issue by arnyeinstein** [hadley/purrr#299]
Hi Hadley
If I use knitr::write_bib with purrr loaded, I get the following warning:
no date field in DESCRIPTION file of package "purrr" could not determine year for "purrr" from package DESCRIPTION file
Nothing serious.
Cheers and thanks for the great work you do.
Renger

**Comment by hadley** [comment]
Yes, that's because there's no date field in the DESCRIPTION, and `write_bib()` doesn't use the built-date which I believe would be more effective.
