### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#35]
It's no longer so directly a port of underscore, and lowliner isn't very evocative

**Comment by hadley** [comment]
lmbdr?

**Comment by lionelgit** [comment]
eleventh?

**Comment by hadley** [comment]
I don't get the reference :(

**Comment by lionelgit** [comment]
lambda is the eleventh letter of the greek alphabet ;)

Lambda Tauri is called like this because it's the eleventh star of the constellation

**Comment by lionelgit** [comment]
What about simply `lambda`? Apparently it's not taken on CRAN.

**Comment by rgrannell1** [comment]
that is very close to [lambda.r](https://github.com/zatonovo/lambda.r), which is another FP library for R.

**Comment by lionel-** [comment]
`purr` would be an awesome package name (and would get many hits on twitter with the hashtag rcatladies)

The reference would be either:
* *pure*, for pure functions
* or in a more tortuous way: *function* → *purpose* → *purr*

Probably too convoluted either way though

**Comment by qinwf** [comment]
funr or funcr funkr funker

**Comment by hadley** [comment]
I like `purrr` or maybe `prrrr`: "Make your pure functions purr with purrr, a functional programming library for R. (Can't remember how many R's to use? The name was chosen to make it line up with dplyr, ggvis and tidyr in your `library()` calls)

**Comment by lionel-** [comment]
:D

**Comment by kevinushey** [comment]
`funnr` -- because it makes functional programming in R more fun? And sometimes we like to pretend that 'funner' is a word?

**Comment by kevinushey** [comment]
`fplyr` -- `plyr` for functional programming!

**Comment by GShotwell** [comment]
From the above, howabout flyr?

**Comment by hadley** [comment]
I like `flyr` (even though it only has four letters), but there was a lot of love for `purrr` on twitter.

**Comment by GShotwell** [comment]
flyer then?

"purrr" will cause many typos, (spot the typo at 3 AM: "purrrr", "purr",
"purrr") and is hard to say.  Another one I thought of was 'lyre'.

**Comment by hadley** [comment]
Spot the typos:

```R
library(dplyr)
library(purrrr)
library(tidyr)
library(purr)
```

;)

**Comment by GShotwell** [comment]
I see you've spent some time thinking about R packages...

**Comment by fayecoga** [comment]
I definitely like  purr

**Comment by datalove** [comment]
I don't think the number of Rs in `purr` is hard to remember if I read it as `pur R` instead of what a cat does.

**Comment by hadley** [comment]
@datalove except it would be `purrr` (i.e. `purr` `R`)

**Comment by lionel-** [comment]
When I look at `purrr::map()`, the part with all the `rrr` looks very blurry to me. Two `rr` would make the library call line up with `httr` ;)

**Comment by lionel-** [comment]
the other advantage of two r is that this way, `purr` can be pronounced *pure*

**Comment by hadley** [comment]
But with three R's you could pronoun it as _purer_

**Comment by smbache** [comment]
That's a good argument: before I was unsure if the name was too "far away"... Purer could reflect that it's "just" purer than regular R, not necessarily completely pure ;-)

As for the *lyr related name suggestions, I think these require prior knowledge about *plyr packages, which I am not sure I like...
