### ISSUE TITLE
Look into implementing Haskell's scanl

### ISSUE THREAD

**Issue by Paradosso** [hadley/purrr#46]
(Reminder for @hadley following a twitter conversation)

From scanl's [documentation](http://zvon.org/other/haskell/Outputprelude/scanl_f.html): It takes the second argument and the first item of the list and applies the function to them, then feeds the function with this result and the second argument and so on. It returns the list of intermediate and final results.

----

It is like fold except it also returns the intermediate results.

**Comment by hadley** [comment]
Maybe call it `creduce()`? Because it's an accumulating reduce?

**Comment by Paradosso** [comment]
Pro: clear that it's (a) cumulative (b) higher-order (can specify your own reducer). Con: the function does not really "reduce" a list/vector to one value, but that's maybe subjective.

**Comment by lionel-** [comment]
How about simply `accumulate()` or maybe `acc()` for short?
