### ISSUE TITLE
Should flatten(list()) return list() instead of NULL?

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#58]
I expected that `flatten()` applied on an empty list would return an empty list rather than `NULL`. This behavior is caused by `unlist()` but I don't find it very intuitive.

I can send a PR to make it return a list instead.

**Comment by lionel-** [comment]
`enlist()` without arguments also returns `NULL`. I think it should return an empty list instead.

**Comment by hadley** [comment]
That seems reasonable to me
