### ISSUE TITLE
Special evaluation functions for list creation and modification?

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#62]
I know the main purpose of purrr is to provide tools for purer functional programming, but maybe a small set of verbs defining a limited DSL for list creation and modification would not hurt.

I'm thinking of having the equivalent of `data_frame()` for lists:
```r
#' Store objects in a list
#'
#' Analog to dplyr's \code{data_frame()} but creates a list instead of
#' a data frame. Thus, no checks are performed on the contents of the
#' list.
#' @export
store <- function(...) {
  store_(lazyeval::lazy_dots(...))
}

#' @rdname store
#' @export
store_ <- function(dots) {
  n <- length(dots)
  dots <- lazyeval::auto_name(dots)

  out <- vector("list", n)
  names(out) <- character(n)
  for (i in seq_len(n)) {
    out[[i]] <- lazyeval::lazy_eval(dots[[i]], out)
    names(out)[i] <- names(dots)[i]
  }
  out
}
```

And we could also have a `mutate()` method to alter lists:
```r
mutate_.list <- function(.data, ..., .dots) {
  dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)

  for (i in seq_along(dots)) {
    .data[[names(dots)[i]]] <- lazyeval::lazy_eval(dots[[i]], .data)
  }

  .data
}
```

**Comment by lionel-** [comment]
hmm just changed the name of this issue from NSE to SE, thinking I was confused... But actually it's the acronym in itself that is confusing.

NSE can mean: non-standard evaluation, which is the same as special evaluation (SE), but could also mean non-special evaluation, which is the complete opposite. No wonder I never know whether to write NSE or SE ;-)

**Comment by lionel-** [comment]
Maybe special evaluation functions should be called R macros. Like lisp macros they operate on unevaluated inputs, and like lisp macros they do not compose well.

**Comment by hadley** [comment]
This is now in dplyr, and might move to tibble.
