### ISSUE TITLE
Create lambdas of several arguments with formula 

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#63]
Hi,

I think I found an elegant way of allowing multiple arguments in lambdas created with formulas. It relies on `..n` being a shortcut for the nth element in `...`

```r
as_function <- function(f) {
  stopifnot(inherits(f, "formula") && length(f) == 2)
  f <- lazyeval::interp(f, .values = list(. = as.name("..1")))
  make_function(alist(... = ), f[[2]], environment(f))
}

as_function(~ ..1 + ..2)(10, 2)
## [1] 12

as_function(~ . + ..2)(10, 2)
## [1] 12
```

Should I document and PR this?

**Comment by hadley** [comment]
Hmmmmmmmmmmmmmmm, it's clever, but I don't know if I like the idea of purely positional arguments.

**Comment by lionel-** [comment]
I think it's ok to match by position here if we consider that lambdas created in this way are meant for simple functions. For more involved applications, the `function(a, b, c) {}` form can still be used.

I also thought about having something like `l(a, b) ~ a + b`, with `l` standing for lambdas. And with a single named argument: `x ~ log(x)`.

But I kind of like the brevity of `~ ..1 + ..2`. Maybe we could have both? Bind dots when no names are specified, and bind the names otherwise?

**Comment by lionel-** [comment]
Oh I just noticed that `a:b:c ~ a+b*c` can also work without special evaluation because `~` has such high precedence

**Comment by lionel-** [comment]
the thing with the `l()` form is that it may feel a bit too magic since `l()` wouldn't be a real function.

**Comment by lionel-** [comment]
Another syntax idea for creating lambdas:

First export a useful definition of `:=`
```r
`:=` <- `~`
```

Then we can have things like:
```r
~arg := 3 * arg
~x ~y := x + y

map(some_object, ~x := {
  do(x)
})

map2(some_object, ~x ~y := {
  do(x, y)
})
```

I think it may be worth it to avoid dots entirely, as they can result in name clashes with magrittr / dplyr and are not   as readable as a named arg.

**Comment by hadley** [comment]
I'm not convinced this is a big improvement over the current design - I rather have people use `function()` for more complicated functions. But it would be nice to have something to use with (e.g.) `map2()` and `map3()`.  I wonder if we could just make the convention a little richer, doing

```R
make_function(alist(x = , y = , z = ), f[[2]], environment(f))
```

That would at least get to 3 args, which I think is a reasonable stopping place. But maybe it would be better to use `.x`, `.y`, and `.z`?

**Comment by lionel-** [comment]
> But maybe it would be better to use .x, .y, and .z?

That sounds good!

**Comment by hadley** [comment]
One place where it doesn't look so nice:

```R
#' 10 %>%
#'   rerun(x = rnorm(5), y = rnorm(5)) %>%
#'   map_v(~ cor(.x$x, .x$y))
```

But you could argue that's a job for `punctuate` anyway.
