### ISSUE TITLE
Issues in Examples

### ISSUE THREAD

**Issue by jarodmeng** [hadley/purrr#65]
In the examples, the `lm()` function doesn't use the `training` sets, but uses `mtcars` all the time.

>boot <- boot %>% mutate(
>  # Fit the models
>  models = map(training, ~ lm(mpg ~ wt, data = **mtcars**)),
>  # Make predictions on test data
>  preds = map2(models, test, predict),
>  diffs = map2(preds, test %>% map("mpg"), msd) 
>)

Should the model fitting line be `models = map(training, ~ lm(mpg ~ wt, data = .)),`?

**Comment by hadley** [comment]
Oops, yes!
