### ISSUE TITLE
power_set_split() ?

### ISSUE THREAD

**Issue by npjc** [hadley/purrr#67]
## Synopsis

`power_set_split()` works just like `split.data.frame()` but generates a list which represents the power set. Compare to the example from the `purrr` documentation: 

``` r
library(dplyr)
library(purrr)
Rcpp::sourceCpp("pwr_set.cpp")

mtcars %>%
  power_set_split(.$cyl) %>%
  map(~ lm(mpg ~ wt, data = .)) %>%
  map(summary) %>%
  map_v("r.squared")

#>        4         6       4∪6         8       4∪8       6∪8     4∪6∪8 
#> 0.5086326 0.4645102 0.6924591 0.4229655 0.7668954 0.6012214 0.7528328 

mtcars %>%
  split(.$cyl) %>%
  map(~ lm(mpg ~ wt, data = .)) %>%
  map(summary) %>%
  map_v("r.squared")

#>        4         6         8 
#> 0.5086326 0.4645102 0.4229655 
```

> here `4∪6` is the subset of row indices which have `cyl == 4 | cyl == 6` (their union/catenate).
### my (likely poor) basic implementation

``` r
power_set_split <- function(x, f, drop = FALSE, naive = TRUE,no_empty_set = TRUE,...) {


  var_splits_ls <- split(x = seq_len(nrow(x)), f = f, drop = drop,...)
  var_splits_names <- names(var_splits_ls)

  if(length(var_splits_names) >= 20 && naive){
    stop("that's more than a million split groupings. If you're sure set naive = FALSE")
  }

  # generate power set from names
  var_power_set_els_ls <- pwr_set_cpp(var_splits_names) 
  # to kepp empty set? 
  if(no_empty_set) {
    var_power_set_els_ls <- var_power_set_els_ls[-1]
  }
  # concatenate reduction with sorting
  var_power_splits_ls <- lapply(var_power_set_els_ls,function(ind) sort(reduce(var_splits_ls[ind],c)))
  names(var_power_splits_ls) <- sapply(var_power_set_els_ls,paste0,collapse='∪')

  lapply(var_power_splits_ls, function(ind) x[ind, , drop = FALSE])
}
```

In `pwr_set.cpp`:

``` c++
#include <Rcpp.h>
#include <Math.h>
using namespace Rcpp;

// [[Rcpp::export]]
List pwr_set_cpp(CharacterVector els) {

  int n_els = els.size();         
  int pwrset_card = pow(2,n_els); 
  List out(pwrset_card);          
  out[0] = StringVector::create(); 
  CharacterVector tmp;            
  int counter = 0;
  for (int i=0; i < n_els; ++i) {
    int cnt2 = counter;            // capture counter state
      for (int j =0; j <= counter; ++j) {
        cnt2++;                   // capture counter + j steps
        tmp = as<StringVector>(out[j]);
        tmp.push_back(as<std::string>(els[i]));
        out[cnt2] = tmp;

    }
      counter = cnt2;             // update counter state
  }
  return out;
}
```

see also: https://github.com/hadley/dplyr/issues/1111

Also then limiting to combinations/supersets of a certain length/cardinality would be handy in a lot of cases too. I definitely have use for this, does future `purrr`?

**Comment by lionel-** [comment]
Hello,

I also think this is needed in purrr.

The idea of applying a function to some combinations of a list is linked to some experiments I did there: #50. The row-based mapping is linked to #51. Also Hadley wrote a `split_by()` function: https://github.com/hadley/purrr/blob/master/R/split_by.R

 Not sure how all of this fits together :-)

**Comment by hadley** [comment]
Agreed - I think this is useful, but it might need to be broken into smaller pieces.  I wonder if it's worth thinking explicitly about iterators, although the iterator here would be a bit strange since it doesn't just iterate over things that all ready exist. 

(I'm hopefully planning to work on purrr again next week, so will have some time to think about these issues then)

**Comment by hadley** [comment]
I'm going to close this for now. I'll keep it in the back of my head, but support for iterators is now feeling out of scope for purrr to me.
