### ISSUE TITLE
[FR] unzip(x,  .simplify = TRUE) handling of NULL behaviour

### ISSUE THREAD

**Issue by npjc** [hadley/purrr#73]
#### Feature Request:

Would it be possible to allow `unzip()` it to coerce NULL? (when there are only two types in an object `NULL` + one of `character`, `integer`, `double`, ...) ?

##### Consider list `x` below:

```r
x <- list(list(foo = "less", bar = "is", baz = "more"), list(foo = "many", bar = "are"))
str(x)
#> List of 2
#> $ :List of 3
#> ..$ foo: chr "less"
#> ..$ bar: chr "is"
#> ..$ baz: chr "more"
#> $ :List of 2                  # no baz here !!
#> ..$ foo: chr "many"
#> ..$ bar: chr "are"
```

##### When I `unzip()` it:

```r
str(x %>% unzip(.simplify =TRUE) 
#> List of 3
#> $ foo: chr [1:2] "less" "many"
#> $ bar: chr [1:2] "is" "are"
#> $ baz:List of 2              # as expected since typeof(NULL) != typeof("more") 
#> ..$ : chr "more"
#> ..$ : NULL
```

##### I would love this behaviour

```r
intended_output <- x %>% unzip(.simplify=TRUE, .coerce_null = TRUE)
str(intended_output)
#> List of 3
#> $ foo: chr [1:2] "less" "many"
#> $ bar: chr [1:2] "is" "are"
#> $ baz: chr [1:2] "more" "NULL"    # or maybe better:  $ baz: chr [1:2] "more" ""
```

```r
intended_output <- x %>% unzip(.simplify=TRUE, .coerce_null = character(1))
str(intended_output)
#> List of 3
#> $ foo: chr [1:2] "less" "many"
#> $ bar: chr [1:2] "is" "are"
#> $ baz: chr [1:2] "more" ""
```

If this worked automagically it would be awesome, otherwise/also if you can specify how to coerce, if required,  for each `.field` that would be very helpful.

**Comment by hadley** [comment]
I now think this is beyond the scope of `transpose()` (previously `unzip()`). If you want to do per-field default values and simplification, you're probably better off using a series of `map_int()`, `map_chr()` etc.  And see #110
