### ISSUE TITLE
Mapping to vectors

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#83]
Just linking to this conversation so we don't forget: https://github.com/hadley/purrr/pull/57#issuecomment-99860375

* Rename `probe()` to `map_chr()` and write `map_lgl()` and `map_num()`.
* Write `as_vector()` for all other cases.
* Should we deprecate `map_v()` then?

This is also linked to the modifications to `can_simplify()` proposed in #42, which need more work.

**Comment by hadley** [comment]
* `probe` becomes `map_lgl()`, right? 
* I'd rather have `map_dbl()` and `map_int()` than `map_num()`
* If we do that, I think we should just get rid of `map_v()`

**Comment by hadley** [comment]
This would also imply changing `invoke_v` for consistency

**Comment by lionel-** [comment]
> probe becomes map_lgl(), right?

ah yes, my mistake.
