### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#84]
@lionel- of the existing issues and PRs, which are the most important? It doesn't matter too much if purrr is incomplete, but changing interfaces is harder once we've released it. If there's anything you think is useful but still need work, we should not export for this release.

@andrie, @piccolbo is there anything in particular that you need in this release that's not already in the dev version?

**Comment by lionel-** [comment]
* There is #14, where I suggested to have `zip()` follow the `fun2()` / `fun3()` / `fun_n()` pattern to avoid the name clash.

* Then #63 with the syntax for lambdas.

* #83 should be easy to complete. Replacing `map_v()` and `probe()` with a bunch of type-specific functions.

* About #42, we don't need to figure out all the composition helpers, but we should at least decide on the name for the successor of `splat()`.

**Comment by piccolbo** [comment]
just closed my only issue, green light from me, thanks

**Comment by lionel-** [comment]
one thing also is that `when()` does not seem to fit in the package very well. It may be more suited to a package focused on implementing partial matching, destructuring bindings, etc. with NSE. Or is purrr ultimately aiming at those things?

**Comment by hadley** [comment]
Yeah, I'm not sure about `when()` either. But I think we can leave it until either purrr expands to cover that sort of functionality, or we find a better home for it

**Comment by hadley** [comment]
Planning to submit to CRAN tomorrow.

**Comment by timelyportfolio** [comment]
:+1:
