### ISSUE TITLE
zip_n() and missing names

### ISSUE THREAD

**Issue by lionel-** [hadley/purrr#97]
Currently, `zip_n()` allows the components names to be different so that:
```r
zip2(list(x = 1), list(y = 2))
## Gives list(x = list(1, NULL))

zip2(list(x = 1), list(y = 2), .fields = c("x", "y"))
## Gives list(x = list(1, NULL), y = list(NULL, 2))
```
This currently fails with atomic vectors, which could be fixed. But I wonder if it would be more generally useful to only use the fields when all components names are equal.

For example, `walk_n()` uses `zip_n()` internally and the current fields handling prevents the following snippet from working correctly:
```r
# Using as.list() to circumvent the bug with vectors
walk2(mtcars, as.list(names(mtcars)), function(col, name) {
  print(paste(name, sum(col)))
})
```

So either we don't change `zip_n()` and fix `walk_n()` not to use it, or we change the fields handling.

Maybe we could have the current behaviour when `.fields` is supplied, and otherwise only use names when they are equal across all components?

**Comment by lionel-** [comment]
I should note that this issue appeared when the fields handling was ported from `unzip()` `to zip_n()`. The old `zip()` function wasn't affected.

**Comment by hadley** [comment]
With the new implementation matching occurs by position for performance. It might be possible to make it make by name instead, but that's going to be considerably more complicated (and slower), and I think if you're using purrr consistently you won't have a mismatched structure.
